import { StrategicActor } from "./types";

// ---------------------------------------------------------------------------
// 15 Fictionalized Strategic Actor Archetypes
// ---------------------------------------------------------------------------
// Brand/Legal Safety:
// - All names are fictionalized. No real company logos or marks.
// - inspiredByCategory references real-world categories neutrally.
// - disclaimer included on every actor.
// ---------------------------------------------------------------------------

export const STRATEGIC_ACTORS: StrategicActor[] = [
  {
    id: "frontier_ai_lab",
    displayName: "OmniAI Labs",
    actorType: "frontier_ai_lab",
    sectorsOfInterest: ["AI / ML", "SaaS", "Healthtech", "Enterprise"],
    preferredStages: ["growth_ready", "raising_series_a", "raising_series_b"],
    investmentRange: { min: 5_000_000, max: 50_000_000 },
    acquisitionRange: { min: 50_000_000, max: 500_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "api_partnership", "acquihire"],
    strategicMotivation: "Acquire foundational technology and talent to advance next-generation models.",
    riskNotes: "High valuation expectations. May shut down standalone product post-acquisition.",
    dealStyle: "aggressive",
    inspiredByCategory: "frontier AI research laboratories",
    disclaimer: "Fictional entity inspired by the frontier AI lab category. Not affiliated with any real company.",
  },
  {
    id: "cloud_hyperscaler",
    displayName: "Northstar Cloud",
    actorType: "cloud_hyperscaler",
    sectorsOfInterest: ["SaaS", "AI / ML", "Fintech", "Gaming", "Enterprise"],
    preferredStages: ["growth_ready", "raising_series_a", "raising_series_b", "strategic_negotiation"],
    investmentRange: { min: 10_000_000, max: 100_000_000 },
    acquisitionRange: { min: 100_000_000, max: 1_000_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "cloud_credits", "platform_integration"],
    strategicMotivation: "Lock in cloud infrastructure demand and expand platform ecosystem.",
    riskNotes: "May require exclusive cloud usage. Long sales cycles for partnership deals.",
    dealStyle: "standard",
    inspiredByCategory: "cloud computing hyperscalers",
    disclaimer: "Fictional entity inspired by the cloud infrastructure category. Not affiliated with any real company.",
  },
  {
    id: "mobile_platform",
    displayName: "Titan Mobile",
    actorType: "mobile_platform",
    sectorsOfInterest: ["Consumer", "Gaming", "Healthtech", "E-commerce"],
    preferredStages: ["growth_ready", "raising_series_a"],
    investmentRange: { min: 2_000_000, max: 20_000_000 },
    acquisitionRange: { min: 20_000_000, max: 200_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "distribution_deal", "platform_integration"],
    strategicMotivation: "Control the app distribution layer and monetize through platform fees.",
    riskNotes: "Heavy platform tax risk. Policy changes can kill business models overnight.",
    dealStyle: "cautious",
    inspiredByCategory: "mobile operating system platforms",
    disclaimer: "Fictional entity inspired by the mobile platform category. Not affiliated with any real company.",
  },
  {
    id: "enterprise_giant",
    displayName: "Apex Dynamics",
    actorType: "enterprise_giant",
    sectorsOfInterest: ["Enterprise", "SaaS", "AI / ML", "Fintech", "Healthtech"],
    preferredStages: ["raising_series_a", "raising_series_b", "strategic_negotiation"],
    investmentRange: { min: 10_000_000, max: 75_000_000 },
    acquisitionRange: { min: 100_000_000, max: 2_000_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "partnership", "platform_integration"],
    strategicMotivation: "Embed startup tech into enterprise stack to defend market position.",
    riskNotes: "Slow integration timelines. Bureaucratic decision-making can delay deals.",
    dealStyle: "standard",
    inspiredByCategory: "enterprise software conglomerates",
    disclaimer: "Fictional entity inspired by the enterprise software category. Not affiliated with any real company.",
  },
  {
    id: "payments_network",
    displayName: "VaultPay Network",
    actorType: "payments_network",
    sectorsOfInterest: ["Fintech", "E-commerce", "SaaS", "Consumer"],
    preferredStages: ["growth_ready", "raising_series_a"],
    investmentRange: { min: 3_000_000, max: 30_000_000 },
    acquisitionRange: { min: 30_000_000, max: 300_000_000 },
    partnershipTypes: ["strategic_investment", "partnership", "api_partnership", "platform_integration"],
    strategicMotivation: "Expand payment volume by owning critical merchant infrastructure.",
    riskNotes: "Regulatory scrutiny. May demand exclusivity in payments processing.",
    dealStyle: "cautious",
    inspiredByCategory: "payment processing networks",
    disclaimer: "Fictional entity inspired by the payments category. Not affiliated with any real company.",
  },
  {
    id: "ecommerce_platform",
    displayName: "Atlas Commerce",
    actorType: "ecommerce_platform",
    sectorsOfInterest: ["E-commerce", "Consumer", "Logistics", "Fintech"],
    preferredStages: ["growth_ready", "raising_series_a", "raising_series_b"],
    investmentRange: { min: 5_000_000, max: 50_000_000 },
    acquisitionRange: { min: 50_000_000, max: 500_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "distribution_deal", "partnership"],
    strategicMotivation: "Own the end-to-end commerce stack from storefront to delivery.",
    riskNotes: "Intense margin pressure. May replicate features internally.",
    dealStyle: "aggressive",
    inspiredByCategory: "global e-commerce marketplaces",
    disclaimer: "Fictional entity inspired by the e-commerce platform category. Not affiliated with any real company.",
  },
  {
    id: "chip_infrastructure",
    displayName: "Cortex Foundry",
    actorType: "chip_infrastructure",
    sectorsOfInterest: ["AI / ML", "Deeptech", "Hardware", "SaaS"],
    preferredStages: ["raising_series_a", "raising_series_b", "strategic_negotiation"],
    investmentRange: { min: 10_000_000, max: 100_000_000 },
    acquisitionRange: { min: 100_000_000, max: 1_000_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "cloud_credits", "partnership"],
    strategicMotivation: "Secure compute demand and vertically integrate the AI stack.",
    riskNotes: "Supply chain dependencies. Capital-intensive partnerships.",
    dealStyle: "standard",
    inspiredByCategory: "semiconductor and AI infrastructure companies",
    disclaimer: "Fictional entity inspired by the chip/infrastructure category. Not affiliated with any real company.",
  },
  {
    id: "healthcare_platform",
    displayName: "Lifeline Data",
    actorType: "healthcare_platform",
    sectorsOfInterest: ["Healthtech", "AI / ML", "Enterprise"],
    preferredStages: ["growth_ready", "raising_series_a"],
    investmentRange: { min: 5_000_000, max: 40_000_000 },
    acquisitionRange: { min: 40_000_000, max: 400_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "partnership", "api_partnership"],
    strategicMotivation: "Control patient data pipelines and clinical decision workflows.",
    riskNotes: "Heavy regulatory burden. HIPAA and FDA compliance requirements.",
    dealStyle: "cautious",
    inspiredByCategory: "healthcare data and platform companies",
    disclaimer: "Fictional entity inspired by the healthcare platform category. Not affiliated with any real company.",
  },
  {
    id: "logistics_operator",
    displayName: "Meridian Freight",
    actorType: "logistics_operator",
    sectorsOfInterest: ["E-commerce", "Consumer", "Logistics", "Climate"],
    preferredStages: ["growth_ready", "raising_series_a"],
    investmentRange: { min: 3_000_000, max: 25_000_000 },
    acquisitionRange: { min: 25_000_000, max: 250_000_000 },
    partnershipTypes: ["strategic_investment", "partnership", "distribution_deal"],
    strategicMotivation: "Own the last-mile delivery and supply chain orchestration layer.",
    riskNotes: "Thin margins. Labor and fuel cost volatility.",
    dealStyle: "standard",
    inspiredByCategory: "logistics and supply chain platforms",
    disclaimer: "Fictional entity inspired by the logistics category. Not affiliated with any real company.",
  },
  {
    id: "social_platform",
    displayName: "Orbit Social",
    actorType: "social_platform",
    sectorsOfInterest: ["Consumer", "Gaming", "E-commerce", "SaaS"],
    preferredStages: ["growth_ready", "raising_series_a"],
    investmentRange: { min: 2_000_000, max: 20_000_000 },
    acquisitionRange: { min: 20_000_000, max: 200_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "distribution_deal", "platform_integration"],
    strategicMotivation: "Keep users inside the ecosystem and monetize attention.",
    riskNotes: "Algorithm dependency. User attention shifts quickly.",
    dealStyle: "aggressive",
    inspiredByCategory: "consumer social media platforms",
    disclaimer: "Fictional entity inspired by the social platform category. Not affiliated with any real company.",
  },
  {
    id: "crypto_exchange",
    displayName: "Prism Exchange",
    actorType: "crypto_exchange",
    sectorsOfInterest: ["Web3", "Fintech", "Gaming", "Consumer"],
    preferredStages: ["growth_ready", "raising_series_a"],
    investmentRange: { min: 2_000_000, max: 30_000_000 },
    acquisitionRange: { min: 20_000_000, max: 300_000_000 },
    partnershipTypes: ["strategic_investment", "partnership", "api_partnership", "platform_integration"],
    strategicMotivation: "Expand token listings and capture DeFi infrastructure.",
    riskNotes: "Regulatory uncertainty. High volatility in crypto markets.",
    dealStyle: "aggressive",
    inspiredByCategory: "cryptocurrency exchanges",
    disclaimer: "Fictional entity inspired by the crypto exchange category. Not affiliated with any real company.",
  },
  {
    id: "cybersecurity_platform",
    displayName: "Sentinel Shield",
    actorType: "cybersecurity_platform",
    sectorsOfInterest: ["SaaS", "Enterprise", "Fintech", "Healthtech"],
    preferredStages: ["growth_ready", "raising_series_a", "raising_series_b"],
    investmentRange: { min: 5_000_000, max: 40_000_000 },
    acquisitionRange: { min: 50_000_000, max: 500_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "partnership", "api_partnership"],
    strategicMotivation: "Consolidate security tooling into a unified platform.",
    riskNotes: "Long enterprise sales cycles. Competing with open-source alternatives.",
    dealStyle: "standard",
    inspiredByCategory: "cybersecurity platform companies",
    disclaimer: "Fictional entity inspired by the cybersecurity category. Not affiliated with any real company.",
  },
  {
    id: "banking_infrastructure",
    displayName: "Pillar Bank",
    actorType: "banking_infrastructure",
    sectorsOfInterest: ["Fintech", "SaaS", "Enterprise", "E-commerce"],
    preferredStages: ["growth_ready", "raising_series_a"],
    investmentRange: { min: 5_000_000, max: 35_000_000 },
    acquisitionRange: { min: 40_000_000, max: 350_000_000 },
    partnershipTypes: ["strategic_investment", "partnership", "api_partnership", "platform_integration"],
    strategicMotivation: "Modernize banking stack by acquiring fintech infrastructure.",
    riskNotes: "Regulatory complexity. Legacy system integration challenges.",
    dealStyle: "cautious",
    inspiredByCategory: "banking infrastructure and BaaS providers",
    disclaimer: "Fictional entity inspired by the banking infrastructure category. Not affiliated with any real company.",
  },
  {
    id: "gaming_publisher",
    displayName: "Nebula Studios",
    actorType: "gaming_publisher",
    sectorsOfInterest: ["Gaming", "Consumer", "AI / ML", "Web3"],
    preferredStages: ["growth_ready", "raising_series_a"],
    investmentRange: { min: 2_000_000, max: 25_000_000 },
    acquisitionRange: { min: 20_000_000, max: 250_000_000 },
    partnershipTypes: ["strategic_investment", "acquisition", "distribution_deal", "partnership"],
    strategicMotivation: "Acquire hit titles and talent to fill content pipeline.",
    riskNotes: "Hit-driven business. Single title failure can tank valuation.",
    dealStyle: "aggressive",
    inspiredByCategory: "video game publishers and studios",
    disclaimer: "Fictional entity inspired by the gaming publisher category. Not affiliated with any real company.",
  },
  {
    id: "energy_infrastructure",
    displayName: "VoltGrid Energy",
    actorType: "energy_infrastructure",
    sectorsOfInterest: ["Climate", "Hardware", "Enterprise", "AI / ML"],
    preferredStages: ["raising_series_a", "raising_series_b", "strategic_negotiation"],
    investmentRange: { min: 10_000_000, max: 80_000_000 },
    acquisitionRange: { min: 100_000_000, max: 800_000_000 },
    partnershipTypes: ["strategic_investment", "partnership", "cloud_credits"],
    strategicMotivation: "Secure energy supply for data centers and edge compute.",
    riskNotes: "Capital intensive. Policy and subsidy dependency.",
    dealStyle: "standard",
    inspiredByCategory: "energy and grid infrastructure companies",
    disclaimer: "Fictional entity inspired by the energy infrastructure category. Not affiliated with any real company.",
  },
];

export function getActorById(id: string): StrategicActor | undefined {
  return STRATEGIC_ACTORS.find((a) => a.id === id);
}

export function getActorsForSector(sector: string): StrategicActor[] {
  return STRATEGIC_ACTORS.filter((a) =>
    a.sectorsOfInterest.some((s) => sector.toLowerCase().includes(s.toLowerCase()))
  );
}
