/**
 * Founder Arena — Mission Library
 *
 * Sector-specific and type-specific mission templates.
 */

import { MissionTemplate } from "./types";

export const MISSION_LIBRARY: MissionTemplate[] = [
  // ─── AI SaaS ─────────────────────────────────────────────────────
  {
    id: "ai_prototype",
    title: "Prototype Core AI Workflow",
    category: "ai_model",
    startupTypes: ["ai_saas", "ai_infrastructure", "healthcare_ai"],
    sectors: ["AI / ML", "Healthtech", "SaaS"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["model_training", "eval_harness"],
    estimatedCost: 25000,
    monthlyCostDelta: 5000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["Working prototype", "Eval metrics defined"],
    failureRisks: ["Model does not converge", "Data quality issues"],
    effectsOnComplete: { productProgressDelta: 15, investorScoreDelta: 3, riskScoreDelta: -2 },
    effectsOnFail: { productProgressDelta: 5, investorScoreDelta: -2, riskScoreDelta: 3 },
    aiPromptContext: "Build a working AI prototype with evaluation metrics.",
  },
  {
    id: "ai_dashboard",
    title: "Build User Dashboard",
    category: "product",
    startupTypes: ["ai_saas", "saas_b2b", "fintech"],
    sectors: ["AI / ML", "SaaS", "Fintech"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Full-stack Engineer", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Product Designer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["frontend", "ux_design"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 4, risk: 2,
    successMetrics: ["Functional dashboard", "User feedback positive"],
    failureRisks: ["UX confusion", "Performance issues"],
    effectsOnComplete: { productProgressDelta: 12, marketScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 4, marketScoreDelta: -2 },
    aiPromptContext: "Create a functional dashboard for users to interact with AI outputs.",
  },
  {
    id: "ai_eval_harness",
    title: "Add Evaluation Harness",
    category: "ai_model",
    startupTypes: ["ai_saas", "ai_infrastructure", "healthcare_ai"],
    sectors: ["AI / ML", "Healthtech"],
    stages: ["pre_seed", "seed"],
    minMonth: 3, maxMonth: 6,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Domain Advisor", seniority: "senior", count: 1 }],
    requiredCapabilities: ["eval_framework", "benchmarking"],
    estimatedCost: 15000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["Automated eval pipeline", "Regression tests"],
    failureRisks: ["Evals do not correlate with user value"],
    effectsOnComplete: { productProgressDelta: 10, investorScoreDelta: 4, riskScoreDelta: -3 },
    effectsOnFail: { productProgressDelta: 3, riskScoreDelta: 2 },
    aiPromptContext: "Build an evaluation harness to measure AI quality over time.",
  },
  {
    id: "ai_private_beta",
    title: "Launch Private Beta",
    category: "launch",
    startupTypes: ["ai_saas", "saas_b2b", "consumer_app"],
    sectors: ["AI / ML", "SaaS", "Consumer"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [
      { role: "Customer Support", seniority: "junior", count: 1 },
      { role: "Marketing Manager", seniority: "mid", count: 1 },
    ],
    requiredCapabilities: ["user_onboarding", "feedback_collection"],
    estimatedCost: 30000,
    monthlyCostDelta: 5000,
    durationMonths: 2,
    complexity: 5, risk: 4,
    successMetrics: ["50+ beta users", "NPS > 30"],
    failureRisks: ["Low engagement", "Critical bugs"],
    effectsOnComplete: { productProgressDelta: 15, revenueDelta: 5000, marketScoreDelta: 5 },
    effectsOnFail: { productProgressDelta: 5, riskScoreDelta: 4, marketScoreDelta: -3 },
    aiPromptContext: "Launch a private beta with feedback collection and onboarding.",
  },
  {
    id: "ai_reduce_inference_cost",
    title: "Reduce Inference Cost",
    category: "operations",
    startupTypes: ["ai_saas", "ai_infrastructure"],
    sectors: ["AI / ML"],
    stages: ["seed", "series_a"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    requiredCapabilities: ["optimization", "caching", "model_compression"],
    estimatedCost: 20000,
    monthlyCostDelta: -3000,
    durationMonths: 2,
    complexity: 6, risk: 3,
    successMetrics: ["50% cost reduction", "Latency < 200ms"],
    failureRisks: ["Quality degradation", "Over-optimization"],
    effectsOnComplete: { burnDelta: -3000, productProgressDelta: 5, investorScoreDelta: 3 },
    effectsOnFail: { burnDelta: 1000, productProgressDelta: -2 },
    aiPromptContext: "Optimize AI inference costs without degrading quality.",
  },
  {
    id: "ai_sign_pilots",
    title: "Sign Paid Pilots",
    category: "sales",
    startupTypes: ["ai_saas", "enterprise_software"],
    sectors: ["AI / ML", "SaaS", "Enterprise"],
    stages: ["seed", "series_a"],
    minMonth: 6, maxMonth: 10,
    requiredRoles: [{ role: "Sales Lead", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    requiredCapabilities: ["enterprise_sales", "pilot_negotiation"],
    estimatedCost: 25000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 6, risk: 5,
    successMetrics: ["3+ paid pilots", "$50K+ committed"],
    failureRisks: ["Long sales cycles", "POC failure"],
    effectsOnComplete: { revenueDelta: 15000, investorScoreDelta: 6, marketScoreDelta: 5 },
    effectsOnFail: { revenueDelta: 2000, investorScoreDelta: -3 },
    aiPromptContext: "Close paid pilot agreements with enterprise customers.",
  },

  // ─── Fintech / Remittance ────────────────────────────────────────
  {
    id: "ftx_define_corridor",
    title: "Define First Corridor",
    category: "product",
    startupTypes: ["fintech", "remittance"],
    sectors: ["Fintech"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    requiredCapabilities: ["market_research", "regulatory_mapping"],
    estimatedCost: 15000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 5, risk: 4,
    successMetrics: ["Corridor selected", "Regulatory map complete"],
    failureRisks: ["Corridor too competitive", "Regulatory blocker"],
    effectsOnComplete: { productProgressDelta: 10, investorScoreDelta: 2, riskScoreDelta: -2 },
    effectsOnFail: { productProgressDelta: 3, riskScoreDelta: 3 },
    aiPromptContext: "Select the first remittance corridor and map regulatory requirements.",
  },
  {
    id: "ftx_ledger",
    title: "Build Ledger / Payment Infrastructure",
    category: "engineering",
    startupTypes: ["fintech", "remittance"],
    sectors: ["Fintech"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Security Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["ledger_design", "transaction_processing"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 3,
    complexity: 7, risk: 5,
    successMetrics: ["Ledger operational", "Audit trail complete"],
    failureRisks: ["Double-spend bugs", "Reconciliation errors"],
    effectsOnComplete: { productProgressDelta: 18, investorScoreDelta: 4, riskScoreDelta: -3 },
    effectsOnFail: { productProgressDelta: 5, riskScoreDelta: 5 },
    aiPromptContext: "Build a secure ledger and payment processing infrastructure.",
  },
  {
    id: "ftx_kyc",
    title: "Add KYC / KYB",
    category: "compliance",
    startupTypes: ["fintech", "remittance", "web3_wallet"],
    sectors: ["Fintech", "Web3"],
    stages: ["pre_seed", "seed"],
    minMonth: 3, maxMonth: 6,
    requiredRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Security Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["kyc_integration", "identity_verification"],
    estimatedCost: 25000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 6, risk: 6,
    successMetrics: ["KYC flow live", "Compliance review passed"],
    failureRisks: ["Rejected by regulator", "Fraud loopholes"],
    effectsOnComplete: { productProgressDelta: 8, investorScoreDelta: 5, riskScoreDelta: -6 },
    effectsOnFail: { productProgressDelta: 2, riskScoreDelta: 6, investorScoreDelta: -3 },
    aiPromptContext: "Implement KYC/KYB flows that pass regulatory scrutiny.",
  },
  {
    id: "ftx_fraud_monitoring",
    title: "Add Fraud / Risk Monitoring",
    category: "security",
    startupTypes: ["fintech", "remittance"],
    sectors: ["Fintech"],
    stages: ["seed", "series_a"],
    minMonth: 5, maxMonth: 8,
    requiredRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["fraud_detection", "transaction_monitoring"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 7, risk: 5,
    successMetrics: ["Real-time monitoring", "False positive < 5%"],
    failureRisks: ["High false positives", "Missed fraud patterns"],
    effectsOnComplete: { productProgressDelta: 8, riskScoreDelta: -8, investorScoreDelta: 4 },
    effectsOnFail: { riskScoreDelta: 5, investorScoreDelta: -2 },
    aiPromptContext: "Build real-time fraud and risk monitoring.",
  },

  // ─── Web3 ────────────────────────────────────────────────────────
  {
    id: "web3_architecture",
    title: "Smart Contract Architecture",
    category: "engineering",
    startupTypes: ["web3_protocol", "web3_wallet"],
    sectors: ["Web3", "Blockchain"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Blockchain Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    requiredCapabilities: ["solidity", "protocol_design", "tokenomics"],
    estimatedCost: 25000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 8, risk: 6,
    successMetrics: ["Architecture doc", "Threat model"],
    failureRisks: ["Reentrancy risk", "Economic attack vector"],
    effectsOnComplete: { productProgressDelta: 14, investorScoreDelta: 4, riskScoreDelta: -2 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 5 },
    aiPromptContext: "Design secure smart contract architecture with threat modeling.",
  },
  {
    id: "web3_mvp_contracts",
    title: "MVP Smart Contracts",
    category: "engineering",
    startupTypes: ["web3_protocol", "web3_wallet"],
    sectors: ["Web3"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Blockchain Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Full-stack Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["smart_contract_dev", "testing"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 3,
    complexity: 7, risk: 6,
    successMetrics: ["Contracts deployed on testnet", "Unit tests > 90%"],
    failureRisks: ["Bugs in core logic", "Gas optimization failure"],
    effectsOnComplete: { productProgressDelta: 16, investorScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 5, riskScoreDelta: 4 },
    aiPromptContext: "Write and test MVP smart contracts for testnet.",
  },
  {
    id: "web3_security_audit",
    title: "Security Audit Prep",
    category: "security",
    startupTypes: ["web3_protocol", "web3_wallet", "fintech"],
    sectors: ["Web3", "Fintech"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Blockchain Engineer", seniority: "senior", count: 1 }],
    requiredCapabilities: ["audit_prep", "bug_bounty_design"],
    estimatedCost: 35000,
    monthlyCostDelta: 5000,
    durationMonths: 2,
    complexity: 7, risk: 5,
    successMetrics: ["Audit report clean", "Critical issues = 0"],
    failureRisks: ["Critical vulnerabilities found", "Expensive fixes"],
    effectsOnComplete: { productProgressDelta: 8, investorScoreDelta: 6, riskScoreDelta: -8 },
    effectsOnFail: { productProgressDelta: 2, riskScoreDelta: 8, investorScoreDelta: -4 },
    aiPromptContext: "Prepare for and pass a smart contract security audit.",
  },
  {
    id: "web3_community_launch",
    title: "Community Launch",
    category: "growth",
    startupTypes: ["web3_protocol", "web3_wallet", "consumer_app"],
    sectors: ["Web3", "Consumer"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 8,
    requiredRoles: [{ role: "Marketing Manager", seniority: "mid", count: 1 }],
    optionalRoles: [
      { role: "Community Manager", seniority: "mid", count: 1 },
      { role: "Product Manager", seniority: "mid", count: 1 },
    ],
    requiredCapabilities: ["community_building", "content_strategy"],
    estimatedCost: 20000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 5, risk: 4,
    successMetrics: ["10K+ community members", "Active devs > 50"],
    failureRisks: ["Low engagement", "Bot infestation"],
    effectsOnComplete: { marketScoreDelta: 6, revenueDelta: 3000, userGrowthDelta: 5000 },
    effectsOnFail: { marketScoreDelta: -2, burnDelta: 2000 },
    aiPromptContext: "Launch and grow a developer and user community.",
  },

  // ─── Healthcare AI ───────────────────────────────────────────────
  {
    id: "health_workflow",
    title: "Prototype Clinical Workflow",
    category: "product",
    startupTypes: ["healthcare_ai"],
    sectors: ["Healthtech"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 4,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Domain Advisor", seniority: "senior", count: 1 }],
    requiredCapabilities: ["clinical_workflow", "model_validation"],
    estimatedCost: 25000,
    monthlyCostDelta: 4000,
    durationMonths: 3,
    complexity: 8, risk: 6,
    successMetrics: ["Workflow validated", "Clinician feedback positive"],
    failureRisks: ["Workflow unsafe", "Clinician rejection"],
    effectsOnComplete: { productProgressDelta: 14, investorScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 5 },
    aiPromptContext: "Prototype a clinical workflow with safety guardrails.",
  },
  {
    id: "health_privacy",
    title: "Privacy / Security Architecture",
    category: "security",
    startupTypes: ["healthcare_ai"],
    sectors: ["Healthtech"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    requiredCapabilities: ["hipaa_compliance", "encryption", "audit_trail"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 7, risk: 7,
    successMetrics: ["HIPAA readiness audit", "Data encryption verified"],
    failureRisks: ["Privacy breach", "Regulatory penalty"],
    effectsOnComplete: { productProgressDelta: 8, riskScoreDelta: -8, investorScoreDelta: 5 },
    effectsOnFail: { riskScoreDelta: 8, investorScoreDelta: -4 },
    aiPromptContext: "Build healthcare-grade privacy and security architecture.",
  },
  {
    id: "health_pilot",
    title: "Run Pilot with Clinic",
    category: "partnership",
    startupTypes: ["healthcare_ai"],
    sectors: ["Healthtech"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "Domain Advisor", seniority: "senior", count: 1 }],
    optionalRoles: [
      { role: "Sales Lead", seniority: "mid", count: 1 },
      { role: "Product Manager", seniority: "mid", count: 1 },
    ],
    requiredCapabilities: ["clinical_validation", "pilot_management"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 3,
    complexity: 7, risk: 5,
    successMetrics: ["Pilot completed", "Outcome data collected"],
    failureRisks: ["Pilot dropout", "No measurable benefit"],
    effectsOnComplete: { productProgressDelta: 12, revenueDelta: 8000, marketScoreDelta: 6 },
    effectsOnFail: { productProgressDelta: 3, marketScoreDelta: -3 },
    aiPromptContext: "Run a clinical pilot and collect validated outcome data.",
  },

  // ─── Consumer / Gaming ───────────────────────────────────────────
  {
    id: "consumer_loop",
    title: "Prototype Core Loop",
    category: "product",
    startupTypes: ["consumer_app", "gaming"],
    sectors: ["Consumer", "Gaming"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Product Designer", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Full-stack Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["game_design", "ux_research", "rapid_prototyping"],
    estimatedCost: 15000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 5, risk: 4,
    successMetrics: ["Core loop playable", "Retention test positive"],
    failureRisks: ["Loop not engaging", "High churn"],
    effectsOnComplete: { productProgressDelta: 12, marketScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 4, marketScoreDelta: -2 },
    aiPromptContext: "Prototype the core engagement loop and test retention.",
  },
  {
    id: "consumer_beta",
    title: "Beta Launch",
    category: "launch",
    startupTypes: ["consumer_app", "gaming"],
    sectors: ["Consumer", "Gaming"],
    stages: ["pre_seed", "seed"],
    minMonth: 3, maxMonth: 6,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [
      { role: "Marketing Manager", seniority: "mid", count: 1 },
      { role: "Customer Support", seniority: "junior", count: 1 },
    ],
    requiredCapabilities: ["launch_coordination", "community_management"],
    estimatedCost: 25000,
    monthlyCostDelta: 5000,
    durationMonths: 2,
    complexity: 5, risk: 5,
    successMetrics: ["10K+ beta users", "D1 retention > 40%"],
    failureRisks: ["Server crash", "Negative reviews"],
    effectsOnComplete: { productProgressDelta: 14, revenueDelta: 3000, userGrowthDelta: 8000 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 4, marketScoreDelta: -3 },
    aiPromptContext: "Launch a public beta with community and support infrastructure.",
  },
  {
    id: "consumer_retention",
    title: "Retention Experiments",
    category: "growth",
    startupTypes: ["consumer_app", "gaming"],
    sectors: ["Consumer", "Gaming"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 8,
    requiredRoles: [{ role: "Product Manager", seniority: "senior", count: 1 }],
    optionalRoles: [
      { role: "Data Engineer", seniority: "mid", count: 1 },
      { role: "Marketing Manager", seniority: "mid", count: 1 },
    ],
    requiredCapabilities: ["ab_testing", "cohort_analysis", "personalization"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["D7 retention +10%", "Churn -15%"],
    failureRisks: ["Experiments inconclusive", "Feature bloat"],
    effectsOnComplete: { productProgressDelta: 8, revenueDelta: 5000, marketScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 2, burnDelta: 2000 },
    aiPromptContext: "Run data-driven retention experiments and personalize user experience.",
  },
  {
    id: "consumer_monetize",
    title: "Monetization Test",
    category: "growth",
    startupTypes: ["consumer_app", "gaming", "marketplace"],
    sectors: ["Consumer", "Gaming", "E-commerce"],
    stages: ["seed"],
    minMonth: 6, maxMonth: 10,
    requiredRoles: [{ role: "Sales Lead", seniority: "mid", count: 1 }],
    optionalRoles: [
      { role: "Product Manager", seniority: "mid", count: 1 },
      { role: "Marketing Manager", seniority: "mid", count: 1 },
    ],
    requiredCapabilities: ["pricing_strategy", "conversion_optimization"],
    estimatedCost: 20000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 5, risk: 4,
    successMetrics: ["ARPU defined", "Conversion > 2%"],
    failureRisks: ["Users churn on paywall", "Price sensitivity"],
    effectsOnComplete: { revenueDelta: 12000, investorScoreDelta: 5, marketScoreDelta: 4 },
    effectsOnFail: { revenueDelta: 1000, marketScoreDelta: -2 },
    aiPromptContext: "Test monetization models and optimize conversion.",
  },

  // ─── Cross-type generic missions ─────────────────────────────────
  {
    id: "generic_security_audit",
    title: "Complete Security Audit",
    category: "security",
    startupTypes: ["saas_b2b", "enterprise_software", "cybersecurity", "fintech", "healthcare_ai"],
    sectors: ["SaaS", "Enterprise", "Fintech", "Healthtech"],
    stages: ["seed", "series_a"],
    minMonth: 4, maxMonth: 9,
    requiredRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Backend Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["security_audit", "vulnerability_assessment"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["Audit passed", "SOC 2 readiness"],
    failureRisks: ["Critical findings", "Expensive remediation"],
    effectsOnComplete: { productProgressDelta: 6, investorScoreDelta: 5, riskScoreDelta: -6 },
    effectsOnFail: { riskScoreDelta: 6, investorScoreDelta: -3 },
    aiPromptContext: "Complete a third-party security audit and address findings.",
  },
  {
    id: "generic_fundraising_prep",
    title: "Prepare for Next Round",
    category: "fundraising",
    startupTypes: ["ai_saas", "saas_b2b", "fintech", "healthcare_ai", "web3_protocol", "enterprise_software"],
    sectors: ["AI / ML", "SaaS", "Fintech", "Healthtech", "Web3", "Enterprise"],
    stages: ["seed"],
    minMonth: 7, maxMonth: 11,
    requiredRoles: [{ role: "Finance/Ops Manager", seniority: "mid", count: 1 }],
    optionalRoles: [
      { role: "CTO", seniority: "senior", count: 1 },
      { role: "Sales Lead", seniority: "senior", count: 1 },
    ],
    requiredCapabilities: ["financial_modeling", "investor_storytelling", "metrics_dashboard"],
    estimatedCost: 20000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["Deck complete", "Metrics narrative strong"],
    failureRisks: ["Weak metrics", "Market downturn"],
    effectsOnComplete: { investorScoreDelta: 8, valuationDelta: 500000 },
    effectsOnFail: { investorScoreDelta: -2 },
    aiPromptContext: "Prepare investor materials and metrics for the next funding round.",
  },
  {
    id: "generic_customer_dev",
    title: "Deep Customer Development",
    category: "research",
    startupTypes: ["ai_saas", "saas_b2b", "fintech", "healthcare_ai", "consumer_app"],
    sectors: ["AI / ML", "SaaS", "Fintech", "Healthtech", "Consumer"],
    stages: ["idea", "pre_seed", "seed"],
    minMonth: 1, maxMonth: 6,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Sales Lead", seniority: "mid", count: 1 }],
    requiredCapabilities: ["customer_interviews", "problem_validation"],
    estimatedCost: 10000,
    monthlyCostDelta: 1000,
    durationMonths: 2,
    complexity: 3, risk: 2,
    successMetrics: ["50+ interviews", "Problem validated"],
    failureRisks: ["No clear pain point", "Wrong persona"],
    effectsOnComplete: { productProgressDelta: 8, marketScoreDelta: 4, riskScoreDelta: -2 },
    effectsOnFail: { productProgressDelta: 2, marketScoreDelta: -2 },
    aiPromptContext: "Conduct deep customer development interviews and validate the problem.",
  },

  // ─── Logistics ───────────────────────────────────────────────────
  {
    id: "logistics_route_opt",
    title: "Route Optimization MVP",
    category: "product",
    startupTypes: ["logistics"],
    sectors: ["Logistics"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["algorithm_design", "geospatial"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["10% route savings", "Sub-second response"],
    failureRisks: ["Algorithm too slow", "Data quality poor"],
    effectsOnComplete: { productProgressDelta: 14, investorScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 4 },
    aiPromptContext: "Build a route optimization MVP that demonstrates measurable delivery savings.",
  },
  {
    id: "logistics_fleet_tracking",
    title: "Fleet Tracking Integration",
    category: "engineering",
    startupTypes: ["logistics"],
    sectors: ["Logistics"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Full-stack Engineer", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "IoT Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["gps_integration", "real_time_data"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["Real-time visibility", "99.5% uptime"],
    failureRisks: ["GPS accuracy issues", "Integration delays"],
    effectsOnComplete: { productProgressDelta: 12, marketScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 3, riskScoreDelta: 3 },
    aiPromptContext: "Integrate fleet tracking to provide real-time shipment visibility.",
  },
  {
    id: "logistics_carrier_onboard",
    title: "Carrier Onboarding Platform",
    category: "sales",
    startupTypes: ["logistics"],
    sectors: ["Logistics"],
    stages: ["pre_seed", "seed"],
    minMonth: 3, maxMonth: 6,
    requiredRoles: [{ role: "Sales Lead", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    requiredCapabilities: ["partner_onboarding", "contract_negotiation"],
    estimatedCost: 20000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 5, risk: 4,
    successMetrics: ["5+ carriers live", "Onboarding < 48h"],
    failureRisks: ["Carriers reluctant", "Competition blocks"],
    effectsOnComplete: { revenueDelta: 8000, investorScoreDelta: 4, marketScoreDelta: 4 },
    effectsOnFail: { revenueDelta: 1000, marketScoreDelta: -2 },
    aiPromptContext: "Onboard carrier partners with a streamlined digital platform.",
  },
  {
    id: "logistics_customs",
    title: "Customs Compliance Automation",
    category: "compliance",
    startupTypes: ["logistics"],
    sectors: ["Logistics"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Backend Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["customs_regulations", "document_automation"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 7, risk: 6,
    successMetrics: ["Clearance time -50%", "Zero customs holds"],
    failureRisks: ["Regulatory change", "Data errors"],
    effectsOnComplete: { productProgressDelta: 8, riskScoreDelta: -6, investorScoreDelta: 4 },
    effectsOnFail: { riskScoreDelta: 6, investorScoreDelta: -3 },
    aiPromptContext: "Automate customs documentation to reduce clearance time and risk.",
  },
  {
    id: "logistics_eta_engine",
    title: "Real-time ETA Engine",
    category: "ai_model",
    startupTypes: ["logistics"],
    sectors: ["Logistics"],
    stages: ["seed", "series_a"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["predictive_modeling", "traffic_data"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 7, risk: 4,
    successMetrics: ["ETA accuracy > 85%", "Customer NPS +10"],
    failureRisks: ["Model drift", "Insufficient training data"],
    effectsOnComplete: { productProgressDelta: 10, marketScoreDelta: 6, investorScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 3, marketScoreDelta: -2 },
    aiPromptContext: "Build an ML-powered ETA engine with live traffic and weather integration.",
  },

  // ─── Energy ──────────────────────────────────────────────────────
  {
    id: "energy_data_pipeline",
    title: "Energy Data Pipeline",
    category: "engineering",
    startupTypes: ["energy"],
    sectors: ["Energy"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Data Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Backend Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["etl_pipeline", "time_series"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["Pipeline live", "Latency < 5 min"],
    failureRisks: ["Source API unstable", "Data gaps"],
    effectsOnComplete: { productProgressDelta: 12, investorScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 3, riskScoreDelta: 4 },
    aiPromptContext: "Build a real-time energy data pipeline from grid operators and IoT sensors.",
  },
  {
    id: "energy_grid_integration",
    title: "Grid Integration Prototype",
    category: "engineering",
    startupTypes: ["energy"],
    sectors: ["Energy"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Security Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["api_integration", "grid_protocols"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 3,
    complexity: 8, risk: 6,
    successMetrics: ["Grid operator connected", "Bidirectional flow tested"],
    failureRisks: ["Protocol mismatch", "Regulatory rejection"],
    effectsOnComplete: { productProgressDelta: 16, investorScoreDelta: 5, riskScoreDelta: -2 },
    effectsOnFail: { productProgressDelta: 5, riskScoreDelta: 6 },
    aiPromptContext: "Prototype grid integration with secure API connections to utility operators.",
  },
  {
    id: "energy_carbon_credits",
    title: "Carbon Credit Validation",
    category: "compliance",
    startupTypes: ["energy"],
    sectors: ["Energy"],
    stages: ["seed"],
    minMonth: 3, maxMonth: 6,
    requiredRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["carbon_accounting", "audit_trail"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 5,
    successMetrics: ["Credits verified", "Registry connected"],
    failureRisks: ["Verification rejected", "Fraud exposure"],
    effectsOnComplete: { investorScoreDelta: 6, riskScoreDelta: -4, revenueDelta: 5000 },
    effectsOnFail: { riskScoreDelta: 6, investorScoreDelta: -3 },
    aiPromptContext: "Validate carbon credits with auditable data trails and third-party verification.",
  },
  {
    id: "energy_demand_forecast",
    title: "Demand Forecasting Model",
    category: "ai_model",
    startupTypes: ["energy"],
    sectors: ["Energy"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["forecasting", "time_series_ml"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 7, risk: 4,
    successMetrics: ["MAPE < 10%", "24h forecast live"],
    failureRisks: ["Seasonal bias", "Data sparsity"],
    effectsOnComplete: { productProgressDelta: 12, marketScoreDelta: 5, investorScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 3, marketScoreDelta: -2 },
    aiPromptContext: "Build a demand forecasting model for energy consumption and generation.",
  },
  {
    id: "energy_utility_partner",
    title: "Utility Partnership",
    category: "partnership",
    startupTypes: ["energy"],
    sectors: ["Energy"],
    stages: ["seed", "series_a"],
    minMonth: 6, maxMonth: 10,
    requiredRoles: [{ role: "Sales Lead", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    requiredCapabilities: ["enterprise_sales", "regulatory_nav"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 3,
    complexity: 7, risk: 6,
    successMetrics: ["Pilot signed", "1M+ households"],
    failureRisks: ["Long procurement", "Incumbent blocks"],
    effectsOnComplete: { revenueDelta: 20000, investorScoreDelta: 8, marketScoreDelta: 6 },
    effectsOnFail: { revenueDelta: 2000, investorScoreDelta: -3 },
    aiPromptContext: "Close a utility partnership pilot with clear technical and commercial terms.",
  },

  // ─── Hardware ────────────────────────────────────────────────────
  {
    id: "hw_pcb_prototype",
    title: "PCB Prototype",
    category: "engineering",
    startupTypes: ["hardware"],
    sectors: ["Hardware"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Hardware Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Firmware Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["pcb_design", "component_sourcing"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 7, risk: 5,
    successMetrics: ["Working PCB", "BOM under target"],
    failureRisks: ["Component shortage", "Design flaw"],
    effectsOnComplete: { productProgressDelta: 14, investorScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 5 },
    aiPromptContext: "Design and fabricate a working PCB prototype within budget.",
  },
  {
    id: "hw_firmware_core",
    title: "Firmware Core",
    category: "engineering",
    startupTypes: ["hardware"],
    sectors: ["Hardware"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Firmware Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Security Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["embedded_c", "rtos", "ota_updates"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 7, risk: 5,
    successMetrics: ["Firmware stable", "OTA working"],
    failureRisks: ["Memory constraints", "Power bugs"],
    effectsOnComplete: { productProgressDelta: 14, investorScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 5 },
    aiPromptContext: "Build stable firmware with over-the-air update capability.",
  },
  {
    id: "hw_manufacturing_partner",
    title: "Manufacturing Partner",
    category: "operations",
    startupTypes: ["hardware"],
    sectors: ["Hardware"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "Operations Manager", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Supply Chain Manager", seniority: "mid", count: 1 }],
    requiredCapabilities: ["contract_manufacturing", "quality_control"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 6, risk: 5,
    successMetrics: ["CM selected", "Quote < target"],
    failureRisks: ["MOQ too high", "Quality issues"],
    effectsOnComplete: { productProgressDelta: 6, investorScoreDelta: 4, riskScoreDelta: -2 },
    effectsOnFail: { riskScoreDelta: 5, investorScoreDelta: -2 },
    aiPromptContext: "Select a contract manufacturer with acceptable MOQ and quality standards.",
  },
  {
    id: "hw_certification",
    title: "FCC / CE Certification",
    category: "compliance",
    startupTypes: ["hardware"],
    sectors: ["Hardware"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 8,
    requiredRoles: [{ role: "Hardware Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    requiredCapabilities: ["rf_testing", "regulatory_submission"],
    estimatedCost: 35000,
    monthlyCostDelta: 5000,
    durationMonths: 2,
    complexity: 7, risk: 6,
    successMetrics: ["Certification passed", "No retests"],
    failureRisks: ["EMI failure", "Expensive retest"],
    effectsOnComplete: { productProgressDelta: 8, riskScoreDelta: -6, investorScoreDelta: 5 },
    effectsOnFail: { riskScoreDelta: 8, investorScoreDelta: -4, burnDelta: 5000 },
    aiPromptContext: "Pass FCC/CE certification on the first attempt with proper pre-testing.",
  },
  {
    id: "hw_beta_ship",
    title: "Beta Hardware Ship",
    category: "launch",
    startupTypes: ["hardware"],
    sectors: ["Hardware"],
    stages: ["seed"],
    minMonth: 6, maxMonth: 10,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [
      { role: "Customer Support", seniority: "junior", count: 1 },
      { role: "Hardware Engineer", seniority: "senior", count: 1 },
    ],
    requiredCapabilities: ["beta_coordination", "feedback_collection"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 6, risk: 5,
    successMetrics: ["100+ units shipped", "NPS > 30"],
    failureRisks: ["Defect rate high", "Logistics delays"],
    effectsOnComplete: { productProgressDelta: 12, marketScoreDelta: 6, revenueDelta: 5000 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 5, marketScoreDelta: -3 },
    aiPromptContext: "Ship beta hardware to early adopters and collect structured feedback.",
  },

  // ─── Developer Tools ─────────────────────────────────────────────
  {
    id: "devtools_cli_mvp",
    title: "CLI MVP",
    category: "product",
    startupTypes: ["developer_tools"],
    sectors: ["Developer Tools"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "DevRel", seniority: "mid", count: 1 }],
    requiredCapabilities: ["cli_design", "developer_ux"],
    estimatedCost: 15000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["CLI installable", "Core command works"],
    failureRisks: ["Platform compatibility", "Poor DX"],
    effectsOnComplete: { productProgressDelta: 12, marketScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 3, marketScoreDelta: -2 },
    aiPromptContext: "Build a developer-friendly CLI MVP with clear documentation.",
  },
  {
    id: "devtools_api_docs",
    title: "API Documentation",
    category: "product",
    startupTypes: ["developer_tools"],
    sectors: ["Developer Tools"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 4,
    requiredRoles: [{ role: "Technical Writer", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Full-stack Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["docs_as_code", "openapi"],
    estimatedCost: 15000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 4, risk: 2,
    successMetrics: ["Interactive docs live", "Code samples tested"],
    failureRisks: ["Docs stale", "Examples broken"],
    effectsOnComplete: { productProgressDelta: 8, marketScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 2, marketScoreDelta: -2 },
    aiPromptContext: "Create interactive API documentation with tested code samples.",
  },
  {
    id: "devtools_sdk_launch",
    title: "SDK Launch",
    category: "launch",
    startupTypes: ["developer_tools"],
    sectors: ["Developer Tools"],
    stages: ["pre_seed", "seed"],
    minMonth: 3, maxMonth: 6,
    requiredRoles: [{ role: "Full-stack Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "DevRel", seniority: "mid", count: 1 }],
    requiredCapabilities: ["sdk_design", "multi_language"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["SDK in 2+ languages", "100+ installs"],
    failureRisks: ["Breaking changes", "Low adoption"],
    effectsOnComplete: { productProgressDelta: 12, marketScoreDelta: 6, userGrowthDelta: 5000 },
    effectsOnFail: { productProgressDelta: 4, marketScoreDelta: -3 },
    aiPromptContext: "Launch an SDK in multiple languages with clear versioning policy.",
  },
  {
    id: "devtools_community",
    title: "Developer Community",
    category: "growth",
    startupTypes: ["developer_tools"],
    sectors: ["Developer Tools"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 8,
    requiredRoles: [{ role: "DevRel", seniority: "mid", count: 1 }],
    optionalRoles: [
      { role: "Community Manager", seniority: "mid", count: 1 },
      { role: "Marketing Manager", seniority: "mid", count: 1 },
    ],
    requiredCapabilities: ["community_building", "content_strategy"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["1K+ community members", "10+ external contributors"],
    failureRisks: ["Low engagement", "Toxic culture"],
    effectsOnComplete: { marketScoreDelta: 6, revenueDelta: 3000, userGrowthDelta: 5000 },
    effectsOnFail: { marketScoreDelta: -2, burnDelta: 2000 },
    aiPromptContext: "Build a thriving developer community with contribution guidelines.",
  },
  {
    id: "devtools_enterprise_sso",
    title: "Enterprise SSO Integration",
    category: "engineering",
    startupTypes: ["developer_tools", "enterprise_software"],
    sectors: ["Developer Tools", "Enterprise"],
    stages: ["seed", "series_a"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Security Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["saml", "oidc", "scim"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["SSO live", "SCIM provisioning"],
    failureRisks: ["IdP incompatibility", "Security review fail"],
    effectsOnComplete: { productProgressDelta: 8, investorScoreDelta: 5, marketScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 2, investorScoreDelta: -2 },
    aiPromptContext: "Implement enterprise SSO with SAML/OIDC and SCIM provisioning.",
  },

  // ─── Marketplace ─────────────────────────────────────────────────
  {
    id: "marketplace_seller_flow",
    title: "Seller Onboarding Flow",
    category: "product",
    startupTypes: ["marketplace"],
    sectors: ["E-commerce"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Full-stack Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["onboarding_design", "kyc_integration"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["Onboarding < 10 min", "80% completion"],
    failureRisks: ["Drop-off high", "Verification slow"],
    effectsOnComplete: { productProgressDelta: 10, marketScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 3, marketScoreDelta: -2 },
    aiPromptContext: "Design a frictionless seller onboarding flow with fast verification.",
  },
  {
    id: "marketplace_escrow",
    title: "Payment Escrow",
    category: "compliance",
    startupTypes: ["marketplace"],
    sectors: ["E-commerce"],
    stages: ["seed"],
    minMonth: 3, maxMonth: 6,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    requiredCapabilities: ["escrow_logic", "money_transmitter"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 7, risk: 6,
    successMetrics: ["Escrow live", "Dispute resolution < 48h"],
    failureRisks: ["Regulatory block", "Fraud exposure"],
    effectsOnComplete: { productProgressDelta: 8, riskScoreDelta: -6, investorScoreDelta: 5 },
    effectsOnFail: { riskScoreDelta: 8, investorScoreDelta: -4 },
    aiPromptContext: "Build a compliant payment escrow with dispute resolution.",
  },
  {
    id: "marketplace_trust",
    title: "Trust & Reviews System",
    category: "security",
    startupTypes: ["marketplace"],
    sectors: ["E-commerce"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "Backend Engineer", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["review_system", "fraud_detection"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 4,
    successMetrics: ["Review authenticity > 95%", "Dispute rate < 2%"],
    failureRisks: ["Fake reviews", "Retaliation"],
    effectsOnComplete: { marketScoreDelta: 6, riskScoreDelta: -4, investorScoreDelta: 3 },
    effectsOnFail: { riskScoreDelta: 5, marketScoreDelta: -3 },
    aiPromptContext: "Build a trustworthy review system with fraud detection.",
  },
  {
    id: "marketplace_matching",
    title: "Supply/Demand Matching",
    category: "ai_model",
    startupTypes: ["marketplace"],
    sectors: ["E-commerce"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["recommendation_engine", "matching_algorithm"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 7, risk: 4,
    successMetrics: ["Match rate +20%", "Conversion +5%"],
    failureRisks: ["Cold start problem", "Bias issues"],
    effectsOnComplete: { revenueDelta: 12000, marketScoreDelta: 5, investorScoreDelta: 4 },
    effectsOnFail: { revenueDelta: 1000, marketScoreDelta: -2 },
    aiPromptContext: "Build an AI matching engine that connects supply and demand efficiently.",
  },

  // ─── Cybersecurity ───────────────────────────────────────────────
  {
    id: "cyber_threat_mvp",
    title: "Threat Detection MVP",
    category: "product",
    startupTypes: ["cybersecurity"],
    sectors: ["Cybersecurity"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Backend Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["threat_intel", "anomaly_detection"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 7, risk: 5,
    successMetrics: ["Detection rate > 90%", "False positive < 5%"],
    failureRisks: ["Alert fatigue", "Evasion techniques"],
    effectsOnComplete: { productProgressDelta: 14, investorScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 5 },
    aiPromptContext: "Build a threat detection MVP with high accuracy and low false positives.",
  },
  {
    id: "cyber_soc2_readiness",
    title: "SOC 2 Readiness",
    category: "compliance",
    startupTypes: ["cybersecurity", "saas_b2b", "enterprise_software"],
    sectors: ["Cybersecurity", "SaaS", "Enterprise"],
    stages: ["pre_seed", "seed"],
    minMonth: 3, maxMonth: 6,
    requiredRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    requiredCapabilities: ["soc2_controls", "policy_documentation"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["Controls implemented", "Auditor engaged"],
    failureRisks: ["Control gaps", "Documentation incomplete"],
    effectsOnComplete: { investorScoreDelta: 6, riskScoreDelta: -6, marketScoreDelta: 4 },
    effectsOnFail: { riskScoreDelta: 6, investorScoreDelta: -3 },
    aiPromptContext: "Achieve SOC 2 readiness with documented controls and policies.",
  },
  {
    id: "cyber_pentest",
    title: "Penetration Testing",
    category: "security",
    startupTypes: ["cybersecurity"],
    sectors: ["Cybersecurity"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Backend Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["penetration_testing", "vulnerability_management"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 7, risk: 5,
    successMetrics: ["Critical findings = 0", "Remediation plan"],
    failureRisks: ["Critical vulnerabilities", "Expensive fixes"],
    effectsOnComplete: { productProgressDelta: 6, investorScoreDelta: 5, riskScoreDelta: -6 },
    effectsOnFail: { riskScoreDelta: 8, investorScoreDelta: -4, burnDelta: 5000 },
    aiPromptContext: "Conduct third-party penetration testing and fix all critical findings.",
  },
  {
    id: "cyber_incident_response",
    title: "Incident Response Playbook",
    category: "operations",
    startupTypes: ["cybersecurity"],
    sectors: ["Cybersecurity"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 8,
    requiredRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Operations Manager", seniority: "mid", count: 1 }],
    requiredCapabilities: ["incident_response", "forensics"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 4,
    successMetrics: ["Playbook documented", "Tabletop exercise passed"],
    failureRisks: ["Gaps in coverage", "Slow response"],
    effectsOnComplete: { riskScoreDelta: -6, investorScoreDelta: 4 },
    effectsOnFail: { riskScoreDelta: 5, investorScoreDelta: -2 },
    aiPromptContext: "Create an incident response playbook and validate it with tabletop exercises.",
  },

  // ─── AI Infrastructure ───────────────────────────────────────────
  {
    id: "aiinfra_model_serving",
    title: "Model Serving API",
    category: "engineering",
    startupTypes: ["ai_infrastructure"],
    sectors: ["AI / ML"],
    stages: ["idea", "pre_seed"],
    minMonth: 1, maxMonth: 3,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "AI Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["api_design", "model_serialization"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["API live", "P95 < 200ms"],
    failureRisks: ["Latency too high", "Model loading slow"],
    effectsOnComplete: { productProgressDelta: 14, investorScoreDelta: 3 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 4 },
    aiPromptContext: "Build a low-latency model serving API with versioning and autoscaling.",
  },
  {
    id: "aiinfra_gpu_optimization",
    title: "GPU Cluster Optimization",
    category: "operations",
    startupTypes: ["ai_infrastructure"],
    sectors: ["AI / ML"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    requiredCapabilities: ["gpu_scheduling", "model_parallelism"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 8, risk: 5,
    successMetrics: ["Utilization > 80%", "Cost per inference -30%"],
    failureRisks: ["Underutilization", "Complex orchestration"],
    effectsOnComplete: { burnDelta: -4000, productProgressDelta: 6, investorScoreDelta: 4 },
    effectsOnFail: { burnDelta: 2000, productProgressDelta: -2 },
    aiPromptContext: "Optimize GPU cluster utilization with intelligent scheduling and batching.",
  },
  {
    id: "aiinfra_finetuning_pipeline",
    title: "Fine-tuning Pipeline",
    category: "ai_model",
    startupTypes: ["ai_infrastructure"],
    sectors: ["AI / ML"],
    stages: ["seed", "series_a"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "AI Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["distributed_training", "experiment_tracking"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 8, risk: 5,
    successMetrics: ["Pipeline automated", "Fine-tune < 24h"],
    failureRisks: ["Training instability", "Data leakage"],
    effectsOnComplete: { productProgressDelta: 14, marketScoreDelta: 5, investorScoreDelta: 5 },
    effectsOnFail: { productProgressDelta: 4, riskScoreDelta: 4 },
    aiPromptContext: "Build an automated fine-tuning pipeline with experiment tracking and rollback.",
  },

  // ─── Enterprise Software ─────────────────────────────────────────
  {
    id: "enterprise_onboarding",
    title: "Enterprise Onboarding",
    category: "product",
    startupTypes: ["enterprise_software", "saas_b2b"],
    sectors: ["Enterprise", "SaaS"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Customer Success", seniority: "mid", count: 1 }],
    requiredCapabilities: ["enterprise_ux", "white_labeling"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["Onboarding < 2 weeks", "Admin controls"],
    failureRisks: ["Complexity too high", "IT rejection"],
    effectsOnComplete: { productProgressDelta: 10, marketScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 3, marketScoreDelta: -2 },
    aiPromptContext: "Design an enterprise onboarding experience with admin controls and SSO.",
  },
  {
    id: "enterprise_sla_monitoring",
    title: "SLA Monitoring",
    category: "operations",
    startupTypes: ["enterprise_software", "saas_b2b"],
    sectors: ["Enterprise", "SaaS"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "DevOps Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["observability", "sla_dashboard"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["SLA dashboard live", "99.9% uptime tracked"],
    failureRisks: ["Alert fatigue", "Blind spots"],
    effectsOnComplete: { productProgressDelta: 8, investorScoreDelta: 3, riskScoreDelta: -3 },
    effectsOnFail: { riskScoreDelta: 4, investorScoreDelta: -2 },
    aiPromptContext: "Build SLA monitoring with customer-facing uptime dashboards.",
  },
  {
    id: "enterprise_soc2_type2",
    title: "SOC 2 Type II",
    category: "compliance",
    startupTypes: ["enterprise_software", "saas_b2b", "cybersecurity"],
    sectors: ["Enterprise", "SaaS", "Cybersecurity"],
    stages: ["seed", "series_a"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Security Engineer", seniority: "senior", count: 1 }],
    requiredCapabilities: ["soc2_type2", "continuous_monitoring"],
    estimatedCost: 35000,
    monthlyCostDelta: 4000,
    durationMonths: 3,
    complexity: 7, risk: 5,
    successMetrics: ["Type II report issued", "Zero exceptions"],
    failureRisks: ["Control failure", "Observation period restart"],
    effectsOnComplete: { investorScoreDelta: 8, riskScoreDelta: -8, marketScoreDelta: 5 },
    effectsOnFail: { riskScoreDelta: 8, investorScoreDelta: -4, burnDelta: 5000 },
    aiPromptContext: "Achieve SOC 2 Type II with a clean audit and no exceptions.",
  },

  // ─── Remittance ──────────────────────────────────────────────────
  {
    id: "remit_fx_hedging",
    title: "FX Hedging Strategy",
    category: "operations",
    startupTypes: ["remittance", "fintech"],
    sectors: ["Fintech"],
    stages: ["seed"],
    minMonth: 4, maxMonth: 7,
    requiredRoles: [{ role: "Finance/Ops Manager", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    requiredCapabilities: ["fx_risk", "treasury_management"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 5,
    successMetrics: ["Hedge ratio > 70%", "FX loss < 1%"],
    failureRisks: ["Currency volatility", "Hedge cost"],
    effectsOnComplete: { riskScoreDelta: -6, investorScoreDelta: 4, revenueDelta: 3000 },
    effectsOnFail: { riskScoreDelta: 6, revenueDelta: -2000 },
    aiPromptContext: "Implement an FX hedging strategy to protect margins from currency volatility.",
  },
  {
    id: "remit_agent_network",
    title: "Agent Network Launch",
    category: "growth",
    startupTypes: ["remittance"],
    sectors: ["Fintech"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 8,
    requiredRoles: [{ role: "Sales Lead", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Operations Manager", seniority: "mid", count: 1 }],
    requiredCapabilities: ["agent_recruitment", "commission_design"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 2,
    complexity: 6, risk: 5,
    successMetrics: ["50+ agents", "$100K monthly flow"],
    failureRisks: ["Agent fraud", "Low liquidity"],
    effectsOnComplete: { revenueDelta: 15000, marketScoreDelta: 6, investorScoreDelta: 5 },
    effectsOnFail: { revenueDelta: 2000, riskScoreDelta: 5 },
    aiPromptContext: "Launch a cash pickup agent network with fraud controls and liquidity management.",
  },
  {
    id: "remit_regulatory_reporting",
    title: "Regulatory Reporting",
    category: "compliance",
    startupTypes: ["remittance", "fintech"],
    sectors: ["Fintech"],
    stages: ["seed", "series_a"],
    minMonth: 6, maxMonth: 10,
    requiredRoles: [{ role: "Compliance Advisor", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["regulatory_reporting", "transaction_monitoring"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 6,
    successMetrics: ["Reports automated", "Zero late filings"],
    failureRisks: ["Data errors", "Regulatory penalty"],
    effectsOnComplete: { riskScoreDelta: -6, investorScoreDelta: 5 },
    effectsOnFail: { riskScoreDelta: 8, investorScoreDelta: -4 },
    aiPromptContext: "Automate regulatory reporting for money transmission with accurate data pipelines.",
  },

  // ─── Gaming ──────────────────────────────────────────────────────
  {
    id: "gaming_multiplayer",
    title: "Multiplayer Backend",
    category: "engineering",
    startupTypes: ["gaming"],
    sectors: ["Gaming"],
    stages: ["pre_seed", "seed"],
    minMonth: 2, maxMonth: 5,
    requiredRoles: [{ role: "Backend Engineer", seniority: "senior", count: 1 }],
    optionalRoles: [{ role: "DevOps Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["real_time_sync", "matchmaking"],
    estimatedCost: 30000,
    monthlyCostDelta: 4000,
    durationMonths: 3,
    complexity: 8, risk: 6,
    successMetrics: ["Matchmaking < 5s", "Lag < 50ms"],
    failureRisks: ["Latency spikes", "Cheating"],
    effectsOnComplete: { productProgressDelta: 16, investorScoreDelta: 4 },
    effectsOnFail: { productProgressDelta: 5, riskScoreDelta: 6 },
    aiPromptContext: "Build a scalable multiplayer backend with low-latency matchmaking.",
  },
  {
    id: "gaming_liveops",
    title: "LiveOps System",
    category: "operations",
    startupTypes: ["gaming"],
    sectors: ["Gaming"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["liveops_tools", "segmentation"],
    estimatedCost: 25000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 6, risk: 4,
    successMetrics: ["Events automated", "Engagement +15%"],
    failureRisks: ["Player fatigue", "Economy imbalance"],
    effectsOnComplete: { revenueDelta: 10000, marketScoreDelta: 5, investorScoreDelta: 3 },
    effectsOnFail: { revenueDelta: 1000, marketScoreDelta: -2 },
    aiPromptContext: "Build a LiveOps system for in-game events and economy management.",
  },

  // ─── Cross-sector generic missions ───────────────────────────────
  {
    id: "generic_pricing_experiment",
    title: "Pricing Experiment",
    category: "growth",
    startupTypes: ["ai_saas", "saas_b2b", "fintech", "consumer_app", "marketplace"],
    sectors: ["AI / ML", "SaaS", "Fintech", "Consumer", "E-commerce"],
    stages: ["seed"],
    minMonth: 5, maxMonth: 9,
    requiredRoles: [{ role: "Product Manager", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["pricing_strategy", "ab_testing"],
    estimatedCost: 15000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["Optimal price found", "Conversion stable"],
    failureRisks: ["Churn spike", "Price sensitivity"],
    effectsOnComplete: { revenueDelta: 10000, marketScoreDelta: 4, investorScoreDelta: 3 },
    effectsOnFail: { revenueDelta: -2000, marketScoreDelta: -2 },
    aiPromptContext: "Run a data-driven pricing experiment to optimize ARPU and conversion.",
  },
  {
    id: "generic_churn_reduction",
    title: "Churn Reduction Program",
    category: "growth",
    startupTypes: ["ai_saas", "saas_b2b", "fintech", "consumer_app"],
    sectors: ["AI / ML", "SaaS", "Fintech", "Consumer"],
    stages: ["seed", "series_a"],
    minMonth: 6, maxMonth: 10,
    requiredRoles: [{ role: "Customer Success", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Data Engineer", seniority: "mid", count: 1 }],
    requiredCapabilities: ["churn_analysis", "retention_campaigns"],
    estimatedCost: 20000,
    monthlyCostDelta: 3000,
    durationMonths: 2,
    complexity: 5, risk: 3,
    successMetrics: ["Churn -20%", "Health score live"],
    failureRisks: ["False positives", "Over-investment"],
    effectsOnComplete: { revenueDelta: 12000, marketScoreDelta: 4, investorScoreDelta: 4 },
    effectsOnFail: { revenueDelta: 1000, marketScoreDelta: -2 },
    aiPromptContext: "Implement a churn reduction program with predictive health scoring.",
  },
  {
    id: "generic_team_scaling",
    title: "Team Scaling Plan",
    category: "operations",
    startupTypes: ["ai_saas", "saas_b2b", "fintech", "enterprise_software", "ai_infrastructure"],
    sectors: ["AI / ML", "SaaS", "Fintech", "Enterprise"],
    stages: ["seed", "series_a"],
    minMonth: 5, maxMonth: 10,
    requiredRoles: [{ role: "HR/People Ops", seniority: "mid", count: 1 }],
    optionalRoles: [{ role: "Finance/Ops Manager", seniority: "mid", count: 1 }],
    requiredCapabilities: ["hiring_process", "onboarding"],
    estimatedCost: 15000,
    monthlyCostDelta: 2000,
    durationMonths: 2,
    complexity: 4, risk: 2,
    successMetrics: ["Hiring plan defined", "Time-to-hire < 30 days"],
    failureRisks: ["Quality drops", "Culture dilution"],
    effectsOnComplete: { investorScoreDelta: 4, riskScoreDelta: -2 },
    effectsOnFail: { investorScoreDelta: -1, riskScoreDelta: 2 },
    aiPromptContext: "Create a scalable hiring and onboarding process for rapid team growth.",
  },
];

const STAGE_COMPATIBILITY: Record<string, string[]> = {
  idea: ["idea", "pre_seed"],
  pre_seed: ["idea", "pre_seed", "seed"],
  seed: ["pre_seed", "seed", "series_a"],
  series_a: ["seed", "series_a", "series_b"],
  series_b: ["series_a", "series_b", "growth"],
  growth: ["series_b", "growth"],
};

export function getMissionsForStartup(
  startupType: string,
  sector: string,
  stage: string,
  currentMonth: number
): MissionTemplate[] {
  const compatibleStages = STAGE_COMPATIBILITY[stage] ?? [stage];

  const eligible = MISSION_LIBRARY.filter((m) => {
    // Type match
    const typeMatch = m.startupTypes.some((t) => startupType.includes(t) || t.includes(startupType));
    // Sector match
    const sectorMatch = m.sectors.some((s) => sector.toLowerCase().includes(s.toLowerCase()));
    // Stage match (with compatibility)
    const stageMatch = m.stages.some((s) => compatibleStages.includes(s));
    // Month range
    const monthMatch =
      (m.minMonth === undefined || currentMonth >= m.minMonth) &&
      (m.maxMonth === undefined || currentMonth <= m.maxMonth);

    return (typeMatch || sectorMatch) && stageMatch && monthMatch;
  });

  // Sort by recommended month range
  return eligible.sort((a, b) => (a.minMonth ?? 0) - (b.minMonth ?? 0));
}
