import { INFRASTRUCTURE_ECONOMY_VERSION, InfrastructureStack, AIUsageTierDefinition } from "./types";

export const INFRASTRUCTURE_STACKS: InfrastructureStack[] = [
  {
    id: "replit_mvp",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "replit",
    title: "Replit MVP",
    description: "Fast prototype stack for idea-stage launches and demoable MVPs.",
    stageFit: ["idea", "prototype", "pre_seed"],
    baseMonthlyCostRange: { min: 0, max: 150 },
    defaultMonthlyCost: 45,
    variableCostDrivers: ["frontend_hosting", "backend_compute", "storage", "build_deploy_usage"],
    reliability: 42,
    scalability: 35,
    security: 38,
    devSpeed: 95,
    complexity: 18,
    investorTrust: 38,
    outageRisk: 58,
    lockInRisk: 42,
    aiReadiness: 45,
    complianceReadiness: 18,
    tags: ["prototype", "fast", "cheap", "outgrown-risk"],
  },
  {
    id: "vercel_serverless",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "vercel",
    title: "Vercel Serverless",
    description: "Frontend and serverless SaaS stack with strong developer speed and scalable launch posture.",
    stageFit: ["prototype", "pre_seed", "seed", "growth"],
    baseMonthlyCostRange: { min: 20, max: 1000 },
    defaultMonthlyCost: 180,
    variableCostDrivers: ["frontend_hosting", "backend_compute", "bandwidth_egress", "storage", "logs_monitoring"],
    reliability: 70,
    scalability: 74,
    security: 64,
    devSpeed: 90,
    complexity: 34,
    investorTrust: 66,
    outageRisk: 36,
    lockInRisk: 62,
    aiReadiness: 62,
    complianceReadiness: 45,
    tags: ["serverless", "frontend", "fast", "bandwidth-risk"],
  },
  {
    id: "render_full_stack",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "render",
    title: "Render Full-Stack",
    description: "Managed full-stack app hosting with predictable services and database-friendly MVP scaling.",
    stageFit: ["prototype", "pre_seed", "seed", "growth"],
    baseMonthlyCostRange: { min: 25, max: 1500 },
    defaultMonthlyCost: 220,
    variableCostDrivers: ["backend_compute", "database", "bandwidth_egress", "storage", "logs_monitoring"],
    reliability: 68,
    scalability: 66,
    security: 62,
    devSpeed: 82,
    complexity: 38,
    investorTrust: 62,
    outageRisk: 38,
    lockInRisk: 48,
    aiReadiness: 58,
    complianceReadiness: 44,
    tags: ["managed", "full-stack", "database", "predictable"],
  },
  {
    id: "supabase_neon_db",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "supabase_neon",
    title: "Supabase/Neon DB Stack",
    description: "Database-forward managed backend for products where auth, Postgres, storage, and data shape the roadmap.",
    stageFit: ["idea", "prototype", "pre_seed", "seed", "growth"],
    baseMonthlyCostRange: { min: 0, max: 1000 },
    defaultMonthlyCost: 140,
    variableCostDrivers: ["database", "storage", "bandwidth_egress", "logs_monitoring"],
    reliability: 62,
    scalability: 60,
    security: 60,
    devSpeed: 86,
    complexity: 30,
    investorTrust: 60,
    outageRisk: 42,
    lockInRisk: 50,
    aiReadiness: 52,
    complianceReadiness: 42,
    tags: ["database", "auth", "postgres", "storage"],
  },
  {
    id: "aws_gcp_scale",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "aws",
    title: "AWS/GCP Scale Stack",
    description: "Cloud-scale managed stack for growth-stage products with serious reliability and scaling needs.",
    stageFit: ["seed", "growth", "series_a", "enterprise"],
    baseMonthlyCostRange: { min: 300, max: 25000 },
    defaultMonthlyCost: 3200,
    variableCostDrivers: [
      "backend_compute",
      "database",
      "storage",
      "bandwidth_egress",
      "logs_monitoring",
      "devops_overhead",
    ],
    reliability: 86,
    scalability: 90,
    security: 82,
    devSpeed: 58,
    complexity: 82,
    investorTrust: 82,
    outageRisk: 22,
    lockInRisk: 70,
    aiReadiness: 70,
    complianceReadiness: 72,
    tags: ["scale", "cloud", "complex", "egress-risk"],
  },
  {
    id: "enterprise_cloud",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "enterprise_cloud",
    title: "Enterprise Cloud Stack",
    description: "High-compliance infrastructure posture for regulated customers, enterprise procurement, and SLA pressure.",
    stageFit: ["growth", "series_a", "enterprise"],
    baseMonthlyCostRange: { min: 12000, max: 150000 },
    defaultMonthlyCost: 28000,
    variableCostDrivers: [
      "backend_compute",
      "database",
      "storage",
      "bandwidth_egress",
      "logs_monitoring",
      "compliance_overhead",
      "devops_overhead",
    ],
    reliability: 94,
    scalability: 92,
    security: 96,
    devSpeed: 42,
    complexity: 94,
    investorTrust: 90,
    outageRisk: 14,
    lockInRisk: 82,
    aiReadiness: 72,
    complianceReadiness: 96,
    tags: ["enterprise", "compliance", "sla", "expensive"],
  },
  {
    id: "ai_heavy_stack",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "ai_heavy_stack",
    title: "AI-Heavy Stack",
    description: "AI-native application stack where token/API usage and inference overhead can outrun hosting costs.",
    stageFit: ["pre_seed", "seed", "growth", "series_a"],
    baseMonthlyCostRange: { min: 500, max: 75000 },
    defaultMonthlyCost: 1800,
    variableCostDrivers: [
      "backend_compute",
      "database",
      "storage",
      "bandwidth_egress",
      "logs_monitoring",
      "llm_api",
      "embeddings",
      "gpu_inference",
    ],
    reliability: 70,
    scalability: 76,
    security: 70,
    devSpeed: 70,
    complexity: 78,
    investorTrust: 78,
    outageRisk: 34,
    lockInRisk: 76,
    aiReadiness: 96,
    complianceReadiness: 58,
    tags: ["ai", "llm", "token-risk", "bill-shock"],
  },
  {
    id: "cheap_static_landing",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "static_landing",
    title: "Cheap Static Landing Stack",
    description: "Static site and waitlist stack for validating demand before serious product infrastructure.",
    stageFit: ["idea", "prototype"],
    baseMonthlyCostRange: { min: 0, max: 40 },
    defaultMonthlyCost: 10,
    variableCostDrivers: ["frontend_hosting", "bandwidth_egress"],
    reliability: 72,
    scalability: 48,
    security: 54,
    devSpeed: 88,
    complexity: 12,
    investorTrust: 34,
    outageRisk: 28,
    lockInRisk: 18,
    aiReadiness: 8,
    complianceReadiness: 12,
    tags: ["static", "landing", "validation", "cheap"],
  },
  {
    id: "cloudflare_edge",
    version: INFRASTRUCTURE_ECONOMY_VERSION,
    provider: "cloudflare",
    title: "Cloudflare Edge Stack",
    description: "Edge-first stack for high-read traffic, global latency, and egress-sensitive workloads.",
    stageFit: ["prototype", "pre_seed", "seed", "growth"],
    baseMonthlyCostRange: { min: 5, max: 1200 },
    defaultMonthlyCost: 160,
    variableCostDrivers: ["frontend_hosting", "backend_compute", "storage", "bandwidth_egress"],
    reliability: 76,
    scalability: 82,
    security: 70,
    devSpeed: 70,
    complexity: 54,
    investorTrust: 62,
    outageRisk: 30,
    lockInRisk: 58,
    aiReadiness: 42,
    complianceReadiness: 42,
    tags: ["edge", "global", "egress-efficient", "optional"],
  },
];

export const AI_USAGE_TIERS: AIUsageTierDefinition[] = [
  {
    id: "none",
    title: "No AI Usage",
    description: "No meaningful LLM/API cost.",
    baseMonthlyCost: 0,
    costMultiplier: 0,
    billShockRisk: 0,
    investorTrustModifier: 0,
    riskScoreModifier: 0,
    warnings: [],
  },
  {
    id: "light",
    title: "Light AI Assist",
    description: "Occasional summaries, small copilots, or internal assistive workflows.",
    baseMonthlyCost: 25,
    costMultiplier: 0.25,
    billShockRisk: 12,
    investorTrustModifier: 1,
    riskScoreModifier: 0,
    warnings: ["Light AI usage is manageable, but output-heavy prompts can still surprise the burn forecast."],
  },
  {
    id: "moderate",
    title: "Moderate AI Workflow",
    description: "Regular AI workflows used by active users or internal operations.",
    baseMonthlyCost: 250,
    costMultiplier: 0.75,
    billShockRisk: 28,
    investorTrustModifier: 2,
    riskScoreModifier: 1,
    warnings: ["AI usage is now a visible burn component. Track requests and output length."],
  },
  {
    id: "heavy",
    title: "Heavy AI Product Core",
    description: "AI is central to the user experience and scales with usage.",
    baseMonthlyCost: 1500,
    costMultiplier: 1.8,
    billShockRisk: 52,
    investorTrustModifier: 4,
    riskScoreModifier: 4,
    warnings: ["Heavy AI usage can exceed hosting and database costs without limits, caching, or pricing power."],
  },
  {
    id: "agentic",
    title: "Agentic Workflows",
    description: "Multi-step agents, tool use, retrieval, and long-context workflows.",
    baseMonthlyCost: 4500,
    costMultiplier: 3.6,
    billShockRisk: 72,
    investorTrustModifier: 5,
    riskScoreModifier: 7,
    warnings: ["Agentic workflows create token, tool, and retry overhead. Bill shock risk is high."],
  },
  {
    id: "multimodal",
    title: "Multimodal / Realtime AI",
    description: "Image, audio, video, realtime, or richer model usage with volatile costs.",
    baseMonthlyCost: 6500,
    costMultiplier: 4.4,
    billShockRisk: 82,
    investorTrustModifier: 5,
    riskScoreModifier: 8,
    warnings: ["Multimodal AI cost volatility is high. Treat this as an advanced stack until unit economics are proven."],
  },
];

export function getInfrastructureStack(stackId: string): InfrastructureStack | undefined {
  return INFRASTRUCTURE_STACKS.find((stack) => stack.id === stackId);
}

export function getAIUsageTierDefinition(tier: string): AIUsageTierDefinition | undefined {
  return AI_USAGE_TIERS.find((definition) => definition.id === tier);
}

