import { InfrastructureEventDefinition } from "./types";

export const INFRASTRUCTURE_EVENT_CATALOG: InfrastructureEventDefinition[] = [
  {
    id: "prototype_outgrown",
    title: "Prototype Outgrown",
    severity: "medium",
    triggerConditions: ["cheap/prototype stack", "monthly active users exceed stack comfort zone", "product progress is high"],
    affectedStats: ["outageRisk", "scalingRisk", "brandTrust"],
    futurePlayerChoices: ["upgrade stack", "optimize traffic", "delay launch"],
    recommendedCounterplay: ["Move from prototype stack to managed full-stack or serverless startup stack."],
    warningCopy: "The MVP stack is no longer absorbing real product traffic.",
    tags: ["prototype", "scaling"],
  },
  {
    id: "serverless_bill_spike",
    title: "Serverless Bill Spike",
    severity: "high",
    triggerConditions: ["serverless stack", "viral traffic volatility", "high requests per user"],
    affectedStats: ["monthlyBurn", "billShockRisk", "investorScore"],
    futurePlayerChoices: ["add caching", "rate limit", "upgrade pricing"],
    recommendedCounterplay: ["Reduce function duration and cache hot paths before the next sprint."],
    warningCopy: "Usage-based serverless costs jumped after traffic spiked.",
    tags: ["serverless", "bill-shock"],
  },
  {
    id: "database_connection_limit",
    title: "Database Connection Limit",
    severity: "medium",
    triggerConditions: ["DB-heavy stack", "high request concurrency", "low database tier"],
    affectedStats: ["outageRisk", "productProgress", "brandRisk"],
    futurePlayerChoices: ["connection pooling", "database upgrade", "queue writes"],
    recommendedCounterplay: ["Add pooling and upgrade database capacity before growth compounds."],
    warningCopy: "Database connection pressure is throttling product reliability.",
    tags: ["database", "reliability"],
  },
  {
    id: "bandwidth_egress_surprise",
    title: "Bandwidth / Egress Surprise",
    severity: "high",
    triggerConditions: ["media-heavy traffic", "viral volatility", "high data transfer"],
    affectedStats: ["monthlyBurn", "billShockRisk", "cash"],
    futurePlayerChoices: ["CDN caching", "compress media", "change stack"],
    recommendedCounterplay: ["Cache, compress, and meter heavy payloads before launch pressure rises."],
    warningCopy: "Egress costs are turning product momentum into burn.",
    tags: ["egress", "media", "bill-shock"],
  },
  {
    id: "logs_observability_spike",
    title: "Logs & Observability Spike",
    severity: "medium",
    triggerConditions: ["high request volume", "verbose logging", "growth-stage traffic"],
    affectedStats: ["monthlyBurn", "devSpeed", "riskScore"],
    futurePlayerChoices: ["sample logs", "set retention policy", "upgrade observability"],
    recommendedCounterplay: ["Reduce noisy logs while preserving incident visibility."],
    warningCopy: "The system is paying to remember too much noise.",
    tags: ["logs", "monitoring"],
  },
  {
    id: "cloud_credits_expiring",
    title: "Cloud Credits Expiring",
    severity: "high",
    triggerConditions: ["credits remaining", "expires in two sprints or less", "gross burn above safe range"],
    affectedStats: ["runway", "monthlyBurn", "boardPressure"],
    futurePlayerChoices: ["raise capital", "optimize infra", "switch providers"],
    recommendedCounterplay: ["Treat gross infra burn as real before credits disappear."],
    warningCopy: "Credits are hiding the real bill. The cliff is close.",
    tags: ["credits", "runway"],
  },
  {
    id: "llm_token_bill_shock",
    title: "LLM Token Bill Shock",
    severity: "critical",
    triggerConditions: ["heavy/agentic/multimodal AI tier", "high AI requests per user", "long output or tool usage"],
    affectedStats: ["monthlyBurn", "riskScore", "investorScore"],
    futurePlayerChoices: ["cache prompts", "limit output", "switch model tier", "charge usage-based pricing"],
    recommendedCounterplay: ["Meter AI features and prove gross margin before scaling traffic."],
    warningCopy: "Token usage is outrunning the startup's pricing model.",
    tags: ["ai", "llm", "bill-shock"],
  },
  {
    id: "gpu_inference_overload",
    title: "GPU Inference Overload",
    severity: "critical",
    triggerConditions: ["self-hosted or multimodal AI", "spiky traffic", "insufficient capacity planning"],
    affectedStats: ["outageRisk", "monthlyBurn", "brandRisk"],
    futurePlayerChoices: ["queue inference", "fallback models", "reserved capacity"],
    recommendedCounterplay: ["Defer self-hosted GPU economics until usage is predictable."],
    warningCopy: "Inference capacity collapsed under uneven demand.",
    tags: ["gpu", "ai", "future"],
  },
  {
    id: "compliance_infrastructure_upgrade",
    title: "Compliance Infrastructure Upgrade",
    severity: "medium",
    triggerConditions: ["regulated or enterprise sector", "enterprise customer target", "low compliance readiness"],
    affectedStats: ["monthlyBurn", "investorTrust", "securityRisk"],
    futurePlayerChoices: ["enterprise cloud", "security audit", "delay enterprise sales"],
    recommendedCounterplay: ["Spend on compliance only when enterprise revenue can justify it."],
    warningCopy: "Enterprise trust requires heavier infrastructure posture.",
    tags: ["compliance", "enterprise"],
  },
  {
    id: "enterprise_reliability_audit",
    title: "Enterprise Reliability Audit",
    severity: "high",
    triggerConditions: ["enterprise deal", "low reliability stack", "high outage risk"],
    affectedStats: ["investorTrust", "revenue", "riskScore"],
    futurePlayerChoices: ["upgrade reliability", "add monitoring", "decline enterprise deal"],
    recommendedCounterplay: ["Match infrastructure maturity to customer expectations."],
    warningCopy: "The customer wants proof the system can survive enterprise traffic.",
    tags: ["enterprise", "reliability", "sales"],
  },
];

export function getInfrastructureEvent(eventId: string): InfrastructureEventDefinition | undefined {
  return INFRASTRUCTURE_EVENT_CATALOG.find((event) => event.id === eventId);
}

