export interface StartupTemplate {
  id: string;
  name: string;
  sector: string;
  region: string;
  description: string;
  targetCustomer: string;
  problem: string;
  solution: string;
  monetizationModel: string;
  unfairAdvantage: string;
  fundingAsk: number;
  riskNote: string;
  whyInteresting: string;
}

export const STARTUP_TEMPLATES: StartupTemplate[] = [
  {
    id: "ai-compliance-copilot",
    name: "ReguLens",
    sector: "AI / ML",
    region: "North America",
    description: "AI-powered compliance copilot that reads regulations and auto-generates policy drafts for fintech and healthcare companies.",
    targetCustomer: "Mid-market fintech and healthtech compliance officers",
    problem: "Compliance teams spend 40+ hours per week manually interpreting new regulations, creating policies, and proving adherence to auditors. Regulatory change velocity has outpaced human bandwidth.",
    solution: "A fine-tuned LLM copilot connected to regulatory feeds (SEC, FDA, GDPR) that drafts policy updates, flags gaps, and generates audit evidence packs in minutes instead of weeks.",
    monetizationModel: "SaaS subscription per compliance seat ($300-800/month) plus audit-prep usage credits.",
    unfairAdvantage: "Founder previously built compliance tooling at a top-10 US bank and has pre-LOIs from three former clients.",
    fundingAsk: 750000,
    riskNote: "High regulatory scrutiny on AI-generated legal advice; need robust hallucination guardrails and human-in-the-loop design.",
    whyInteresting: "High AI sector exposure means valuation spikes in boom markets, but regulation crackdowns can spike risk scores. Great for learning how sector timing affects investor appetite.",
  },
  {
    id: "stablecoin-remittance",
    name: "BridgeSend",
    sector: "Fintech",
    region: "Latin America",
    description: "Stablecoin remittance platform for migrant workers sending money home with near-zero fees and instant settlement.",
    targetCustomer: "Migrant workers in the US and EU sending remittances to LATAM and Southeast Asia",
    problem: "Traditional remittance corridors charge 6-12% fees and take 2-5 days. Recipients in rural areas face high cash-out costs and FX slippage.",
    solution: "A mobile app that on-ramps fiat to stablecoins, routes via low-cost L2 networks, and off-ramps to local mobile money or bank accounts with sub-1% fees and sub-10-minute settlement.",
    monetizationModel: "Small FX spread (0.5-1%) plus B2B API fees for neobanks and payroll platforms.",
    unfairAdvantage: "Co-founder ran a money-services business in Mexico for 5 years with existing agent network relationships.",
    fundingAsk: 1200000,
    riskNote: "Crypto bear markets crush stablecoin trust; regulatory bans on crypto remittances in key corridors could be fatal.",
    whyInteresting: "Exposes players to crypto market volatility and fintech regulatory risk. Strong in crypto bull markets, vulnerable in bearish or high-regulation scenarios.",
  },
  {
    id: "web3-wallet-security",
    name: "VaultGuard",
    sector: "Fintech",
    region: "Remote / Global",
    description: "Web3 wallet security tool that simulates transactions before signing to detect scams, phishing, and smart-contract exploits.",
    targetCustomer: "Retail DeFi users, NFT traders, and crypto-native small funds",
    problem: "$3.8B was lost to crypto scams and hacks last year. Most users cannot read smart contract code and sign malicious transactions without realizing it.",
    solution: "Browser extension and mobile SDK that simulates every transaction outcome before signing, flags suspicious approval patterns, and maintains a real-time threat intelligence database of malicious contracts.",
    monetizationModel: "Freemium for retail; enterprise API for wallets and exchanges ($2-5k/month).",
    unfairAdvantage: "Technical co-founder previously worked at a leading blockchain security firm and maintains relationships with white-hat hacker networks.",
    fundingAsk: 900000,
    riskNote: "Web3 security is a crowded space; incumbents have brand trust. Need continuous threat-intel freshness to stay relevant.",
    whyInteresting: "Tight coupling to crypto market sentiment. Bull markets drive user growth; bear markets make customer acquisition expensive. Teaches players about sector cyclicality.",
  },
  {
    id: "vertical-saas-clinics",
    name: "ClinicFlow",
    sector: "Healthtech",
    region: "Europe",
    description: "Vertical SaaS for independent clinics handling scheduling, billing, patient records, and regulatory reporting in one lightweight platform.",
    targetCustomer: "Independent medical and dental clinics with 2-15 practitioners",
    problem: "Small clinics cobble together 4-6 disjointed tools (scheduling, billing, EHR, reporting). Integration overhead costs 10+ hours per week and creates compliance gaps under GDPR and local health regulations.",
    solution: "An all-in-one clinic OS with scheduling, billing, lightweight EHR, and auto-generated regulatory reports. GDPR-compliant by default with local data residency options.",
    monetizationModel: "Per-practitioner subscription (€80-150/month) plus billing-transaction revenue share (0.5%).",
    unfairAdvantage: "Founder is a former clinic operations manager with 200+ practitioner LinkedIn connections and two pilot LOIs signed.",
    fundingAsk: 600000,
    riskNote: "Healthcare sales cycles are long; GDPR compliance costs are front-loaded. Need strong initial pilot traction to prove unit economics.",
    whyInteresting: "Steady, defensive sector with moderate growth. Teaches players about slower but more predictable markets and the value of vertical SaaS moats.",
  },
  {
    id: "ai-sales-assistant",
    name: "PitchForge",
    sector: "AI / ML",
    region: "North America",
    description: "AI sales assistant that researches prospects, drafts personalized outreach, and coaches reps on objection handling using call transcripts.",
    targetCustomer: "B2B SaaS sales teams with 10-100 reps",
    problem: "Sales reps spend 60% of their time on non-selling activities: research, CRM data entry, and drafting emails. Personalization at scale is expensive and inconsistent.",
    solution: "An AI agent that auto-researches prospects from public data, drafts hyper-personalized sequences, logs CRM activity, and provides real-time call coaching based on top-performer transcript patterns.",
    monetizationModel: "Per-seat SaaS ($150-400/month) with enterprise tiers for call coaching and CRM integrations.",
    unfairAdvantage: "Founder previously led sales ops at a unicorn SaaS company and has a dataset of 50k+ anonymized sales call transcripts under license.",
    fundingAsk: 1000000,
    riskNote: "AI sales tools are becoming commoditized; differentiation requires unique data assets or workflow depth. Churn can be high if ROI is not immediate.",
    whyInteresting: "Strong in enterprise spending expansion markets, vulnerable in recessions when sales hiring freezes. Good for learning how B2B demand cycles affect SaaS startups.",
  },
  {
    id: "climate-energy-saas",
    name: "GridWise",
    sector: "Climate",
    region: "Europe",
    description: "Climate/energy optimization SaaS that helps commercial buildings reduce electricity costs using IoT sensor data and predictive load balancing.",
    targetCustomer: "Facility managers of commercial real estate and light industrial buildings (10k-100k sq ft)",
    problem: "Commercial buildings waste 30% of their energy due to poor HVAC scheduling and lack of real-time load optimization. Energy price volatility makes budgeting impossible.",
    solution: "IoT sensor network + ML platform that predicts occupancy, optimizes HVAC and lighting schedules, and shifts flexible loads to off-peak pricing windows.",
    monetizationModel: "Hardware + SaaS: sensor kit upfront ($2-5k per building) plus monthly optimization fee ($500-2k per building) with savings-share tier.",
    unfairAdvantage: "Co-founder holds patents in building energy optimization from PhD research; pilot customer is a top-5 European property manager.",
    fundingAsk: 1500000,
    riskNote: "Hardware complexity increases burn and operational risk. Energy price spikes help ROI narrative but supply chain crises can delay deployments.",
    whyInteresting: "Tied to energy price and climate policy scenarios. Strong tailwinds during energy crises and green subsidy booms. Teaches players about hardware+software business model complexity.",
  },
  {
    id: "gaming-creator-economy",
    name: "StreamForge",
    sector: "Consumer",
    region: "Asia",
    description: "Gaming creator economy tool that lets streamers mint clips as NFTs, run fan token communities, and monetize via micro-tournaments.",
    targetCustomer: "Mid-tier gaming streamers (10k-500k followers) and their fan communities",
    problem: "Streamers rely on volatile ad revenue and platform algorithms. Fans want deeper engagement and ownership, but existing tools are fragmented and high-friction.",
    solution: "All-in-one creator platform: automatic clip-to-NFT minting, no-code fan token launch, integrated micro-tournament hosting with entry fees and prize pools.",
    monetizationModel: "Platform fee on NFT sales (5%), tournament rake (10%), and fan token transaction fees (1%).",
    unfairAdvantage: "Co-founder is a former top-100 Twitch streamer with 2M+ followers who can drive initial supply-side adoption.",
    fundingAsk: 800000,
    riskNote: "Crypto and NFT sentiment is highly cyclical. Platform dependency on Twitch/YouTube APIs creates regulatory and policy risk.",
    whyInteresting: "Extreme sensitivity to crypto bull/bear markets and consumer spending. Teaches players about high-beta consumer crypto products and the importance of diversification.",
  },
  {
    id: "logistics-visibility",
    name: "CargoLens",
    sector: "Enterprise",
    region: "North America",
    description: "Logistics visibility platform that aggregates ocean, air, and trucking data into a single real-time map with predictive delay alerts.",
    targetCustomer: "Mid-market freight forwarders and importers with 50+ containers per month",
    problem: "Supply chain visibility is fragmented across carriers, ports, and brokers. Delays are detected too late, causing stock-outs and expedited freight costs.",
    solution: "Unified visibility layer that normalizes data from 80+ carriers and ports, predicts delays using ML on weather and congestion data, and auto-alerts stakeholders with rerouting recommendations.",
    monetizationModel: "Per-shipment tracking fee ($2-5) plus enterprise subscription for predictive analytics ($1-3k/month).",
    unfairAdvantage: "Founder previously built carrier integrations at a major logistics API company and owns the relationship playbook for top-20 ocean lines.",
    fundingAsk: 1100000,
    riskNote: "Supply chain crises increase demand but also fragment data sources further. Carrier API reliability is a constant operational headache.",
    whyInteresting: "Directly tied to supply chain crisis and geopolitical risk scenarios. Demand spikes during disruptions but so do operational costs. Great for learning about counter-cyclical demand patterns.",
  },
  {
    id: "consumer-finance-app",
    name: "FinPath",
    sector: "Fintech",
    region: "North America",
    description: "Consumer finance app that aggregates debts, negotiates lower rates via AI, and automates payoff strategies for millennials and Gen Z.",
    targetCustomer: "Millennials and Gen Z with $10k-100k in consumer debt (credit cards, student loans, buy-now-pay-later)",
    problem: "Young consumers juggle 4-7 debt accounts with varying rates and terms. They overpay by thousands annually because they lack time and negotiation confidence to optimize.",
    solution: "Mobile app that aggregates all debts, simulates payoff strategies (avalanche, snowball, hybrid), and auto-negotiates lower APRs or balance transfer offers via AI-powered lender communication.",
    monetizationModel: "Freemium planning; success fee on negotiated savings (15-25% of first-year savings) plus affiliate commissions on refinancing.",
    unfairAdvantage: "Founder previously built credit-risk models at a major neobank and has pre-negotiated API access to three lending partners.",
    fundingAsk: 850000,
    riskNote: "Consumer finance is heavily regulated; need compliance infrastructure early. Economic downturns increase demand but also default risk.",
    whyInteresting: "Counter-cyclical demand during recessions but higher default risk. Teaches players about regulated consumer fintech and the trade-offs between growth and risk in downturns.",
  },
  {
    id: "developer-api-testing",
    name: "MockSmith",
    sector: "SaaS",
    region: "Remote / Global",
    description: "Developer tool for API testing that generates realistic mock servers, contract tests, and performance benchmarks from OpenAPI specs.",
    targetCustomer: "Backend engineering teams at growth-stage SaaS companies (20-200 engineers)",
    problem: "Engineers waste 20-30% of sprint time building and maintaining mock servers, flaky integration tests, and load-test fixtures. Existing tools are either too simple or require heavy infrastructure.",
    solution: "CLI and cloud platform that ingests OpenAPI specs, generates deterministic mock servers with realistic synthetic data, auto-creates contract tests, and runs performance benchmarks against SLAs.",
    monetizationModel: "Per-engineer SaaS ($20-40/month) with enterprise tiers for on-premise deployment and advanced load testing.",
    unfairAdvantage: "Founder is a well-known open-source maintainer of a popular API tooling library with 15k+ GitHub stars and existing community trust.",
    fundingAsk: 700000,
    riskNote: "Developer tooling has low switching costs and price-sensitive buyers. Need to build workflow lock-in via CI/CD integrations quickly.",
    whyInteresting: "Steady SaaS sector with predictable unit economics. Teaches players about bottom-up developer adoption, open-source monetization, and the importance of CI/CD ecosystem integrations.",
  },
  {
    id: "healthcare-ai-triage",
    name: "TriageAI",
    sector: "Healthtech",
    region: "North America",
    description: "Healthcare AI triage assistant that helps primary care clinics prioritize patient appointments based on symptom severity and resource availability.",
    targetCustomer: "Primary care clinics and urgent care chains with 5-50 locations",
    problem: "Primary care clinics are overwhelmed with patient volume. Non-urgent cases clog scheduling, while urgent cases face dangerous wait times. Triage nurses are expensive and inconsistently available.",
    solution: "AI triage module integrated into clinic EHRs that analyzes patient-reported symptoms, medical history, and real-time clinic capacity to recommend appointment urgency and care setting.",
    monetizationModel: "Per-clinic subscription ($500-1,500/month) plus per-triage usage fees for overflow and after-hours coverage.",
    unfairAdvantage: "Clinical co-founder is a board-certified emergency physician with health system executive experience and existing EHR vendor relationships.",
    fundingAsk: 1300000,
    riskNote: "Medical liability for AI triage decisions is a major concern. Need FDA/risk-classification clarity and robust clinical validation studies.",
    whyInteresting: "Strong in healthcare AI tailwind scenarios but vulnerable to regulatory crackdowns. Teaches players about the tension between AI innovation and healthcare compliance.",
  },
  {
    id: "local-services-marketplace",
    name: "NeighborNest",
    sector: "Consumer",
    region: "Latin America",
    description: "Marketplace for local services connecting homeowners with vetted cleaners, handymen, and tutors with transparent pricing and insurance-backed guarantees.",
    targetCustomer: "Middle-class urban homeowners in LATAM megacities",
    problem: "Finding reliable local service providers is trust-intensive and time-consuming. Informal markets dominate, leading to no-shows, price haggling, and quality variance.",
    solution: "A marketplace that vets providers via background checks and skill tests, displays fixed transparent pricing, offers insurance-backed satisfaction guarantees, and handles scheduling and payment.",
    monetizationModel: "Commission on bookings (15-20%) plus premium provider subscriptions for priority placement ($30-80/month).",
    unfairAdvantage: "Founder previously scaled a similar marketplace to $5M GMV in another emerging market and has a playbook for provider acquisition and trust-building.",
    fundingAsk: 650000,
    riskNote: "Marketplace businesses require simultaneous supply and demand growth. Consumer recession scenarios reduce discretionary service spending.",
    whyInteresting: "Classic marketplace dynamics teach players about two-sided network effects, take-rate optimization, and how consumer recessions affect discretionary spending categories.",
  },
];

export function getTemplateById(id: string): StartupTemplate | undefined {
  return STARTUP_TEMPLATES.find((t) => t.id === id);
}

export function getFundingAskGuidance(sector: string): string {
  const guidance: Record<string, string> = {
    "AI / ML": "AI/ML startups typically raise $750K-$1.5M for initial model training and compute credits.",
    "Fintech": "Fintech startups often need $800K-$1.2M for compliance infrastructure and banking partnerships.",
    "Healthtech": "Healthtech usually requires $600K-$1.3M for regulatory validation and pilot deployments.",
    "SaaS": "SaaS startups can launch with $500K-$900K focused on product development and early GTM.",
    "Consumer": "Consumer apps need $600K-$1M for user acquisition and community building.",
    "Enterprise": "Enterprise startups typically raise $900K-$1.5M for sales cycles and integration work.",
    "Climate": "Climate/energy startups often need $1M-$2M for hardware prototypes and pilot installations.",
    "E-commerce": "E-commerce ventures can start with $400K-$800K for inventory and logistics setup.",
    "EdTech": "EdTech startups usually raise $500K-$1M for content development and institutional sales.",
    "Other": "Most early-stage startups raise between $500K and $1M for their first 12-18 months.",
  };
  return guidance[sector] ?? guidance["Other"];
}
