import { MarketScenario } from "./types";

const BASE_MACRO = {
  vcClimate: 0,
  inflationPressure: 0,
  geopoliticalRisk: 0,
  consumerSpending: 0,
  enterpriseSpending: 0,
  aiDemand: 0,
  cryptoSentiment: 0,
  regulationPressure: 0,
  supplyChainPressure: 0,
  energyPrices: 0,
};

export const SCENARIOS: MarketScenario[] = [
  {
    key: "neutral_market",
    name: "Steady State",
    description: "Markets are balanced. No major headwinds or tailwinds.",
    condition: "neutral",
    macro: { ...BASE_MACRO },
    sectorModifiers: {},
    event: {
      name: "Steady Markets",
      description: "Global markets remain stable with moderate activity.",
      type: "neutral",
      severity: 20,
      affectedSectors: [],
      affectedRegions: [],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "ai_boom",
    name: "AI Boom",
    description: "AI demand is surging. Enterprise buyers are rushing to adopt.",
    condition: "bullish",
    macro: {
      ...BASE_MACRO,
      vcClimate: 40,
      aiDemand: 80,
      enterpriseSpending: 30,
      consumerSpending: 10,
    },
    sectorModifiers: {
      "ai": { demandDelta: 25, revenueDelta: 20, burnDelta: 5, valuationDelta: 25, investorDelta: 15, riskDelta: -5, productDelta: 10 },
      "saas": { demandDelta: 10, revenueDelta: 8, burnDelta: 0, valuationDelta: 10, investorDelta: 5, riskDelta: 0 },
      "healthcare": { demandDelta: 5, revenueDelta: 4, burnDelta: 0, valuationDelta: 5, investorDelta: 3, riskDelta: 0 },
    },
    event: {
      name: "Generative AI Investment Surge",
      description: "VCs are pouring capital into AI startups. Enterprise procurement cycles have accelerated for AI-native tools.",
      type: "positive",
      severity: 70,
      affectedSectors: ["AI / ML", "SaaS", "Enterprise Software"],
      affectedRegions: ["North America", "Europe", "Asia"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "high_interest_rates",
    name: "Tight Money",
    description: "Central banks have raised rates. Capital is expensive and valuations are compressing.",
    condition: "bearish",
    macro: {
      ...BASE_MACRO,
      vcClimate: -50,
      inflationPressure: 40,
      consumerSpending: -20,
      enterpriseSpending: -10,
    },
    sectorModifiers: {
      "fintech": { demandDelta: -15, revenueDelta: -10, burnDelta: 0, valuationDelta: -20, investorDelta: -15, riskDelta: 10 },
      "saas": { demandDelta: -5, revenueDelta: -5, burnDelta: 0, valuationDelta: -15, investorDelta: -10, riskDelta: 5 },
      "web3": { demandDelta: -20, revenueDelta: -15, burnDelta: 0, valuationDelta: -25, investorDelta: -20, riskDelta: 15 },
    },
    event: {
      name: "Rate Hike Cycle Continues",
      description: "Benchmark rates at decade highs. Late-stage funding has dried up and down rounds are common.",
      type: "negative",
      severity: 75,
      affectedSectors: ["Fintech", "SaaS", "Web3", "PropTech"],
      affectedRegions: ["North America", "Europe"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "geopolitical_conflict",
    name: "Global Tensions",
    description: "Major geopolitical conflict is disrupting trade and creating uncertainty.",
    condition: "bearish",
    macro: {
      ...BASE_MACRO,
      geopoliticalRisk: 70,
      supplyChainPressure: 50,
      energyPrices: 40,
      vcClimate: -20,
      consumerSpending: -15,
    },
    sectorModifiers: {
      "energy": { demandDelta: 10, revenueDelta: 8, burnDelta: 3, valuationDelta: 5, investorDelta: 3, riskDelta: 5 },
      "supply_chain": { demandDelta: -10, revenueDelta: -8, burnDelta: 5, valuationDelta: -10, investorDelta: -8, riskDelta: 15 },
      "defense": { demandDelta: 15, revenueDelta: 12, burnDelta: 0, valuationDelta: 10, investorDelta: 8, riskDelta: 0 },
    },
    event: {
      name: "Trade Restrictions and Energy Shock",
      description: "Export controls and shipping disruptions are raising costs. Defense and energy sectors see inflows.",
      type: "negative",
      severity: 80,
      affectedSectors: ["Manufacturing", "Logistics", "Energy", "Defense"],
      affectedRegions: ["Europe", "Asia", "Middle East"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "crypto_bull_market",
    name: "Crypto Bull Run",
    description: "Digital assets are surging. Web3 funding and consumer interest are back.",
    condition: "bullish",
    macro: {
      ...BASE_MACRO,
      cryptoSentiment: 80,
      vcClimate: 30,
      consumerSpending: 10,
    },
    sectorModifiers: {
      "web3": { demandDelta: 30, revenueDelta: 25, burnDelta: -5, valuationDelta: 35, investorDelta: 20, riskDelta: -10 },
      "fintech": { demandDelta: 5, revenueDelta: 5, burnDelta: 0, valuationDelta: 5, investorDelta: 3, riskDelta: 0 },
      "gaming": { demandDelta: 10, revenueDelta: 8, burnDelta: 0, valuationDelta: 10, investorDelta: 5, riskDelta: -2 },
    },
    event: {
      name: "Crypto Rally and ETF Inflows",
      description: "Institutional crypto products are seeing record inflows. Web3 startups are raising at premium valuations again.",
      type: "positive",
      severity: 65,
      affectedSectors: ["Web3", "DeFi", "Gaming", "Fintech"],
      affectedRegions: ["North America", "Asia", "Europe"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "crypto_bear_market",
    name: "Crypto Winter",
    description: "Digital assets have crashed. Web3 funding is frozen and regulators are circling.",
    condition: "bearish",
    macro: {
      ...BASE_MACRO,
      cryptoSentiment: -70,
      vcClimate: -30,
      regulationPressure: 30,
      consumerSpending: -10,
    },
    sectorModifiers: {
      "web3": { demandDelta: -30, revenueDelta: -25, burnDelta: 0, valuationDelta: -35, investorDelta: -20, riskDelta: 20 },
      "gaming": { demandDelta: -5, revenueDelta: -5, burnDelta: 0, valuationDelta: -5, investorDelta: -3, riskDelta: 3 },
    },
    event: {
      name: "Exchange Collapse and Regulatory Crackdown",
      description: "Major exchange failure triggered a cascade. Regulators are proposing strict custody and stablecoin rules.",
      type: "negative",
      severity: 85,
      affectedSectors: ["Web3", "DeFi", "Crypto", "Gaming"],
      affectedRegions: ["North America", "Europe", "Asia"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "fintech_regulatory_crackdown",
    name: "Regulatory Storm",
    description: "Financial regulators are tightening rules across lending, payments, and crypto.",
    condition: "bearish",
    macro: {
      ...BASE_MACRO,
      regulationPressure: 70,
      vcClimate: -20,
    },
    sectorModifiers: {
      "fintech": { demandDelta: -20, revenueDelta: -15, burnDelta: 5, valuationDelta: -20, investorDelta: -15, riskDelta: 20 },
      "crypto": { demandDelta: -15, revenueDelta: -10, burnDelta: 3, valuationDelta: -15, investorDelta: -10, riskDelta: 15 },
      "saas": { demandDelta: -2, revenueDelta: -2, burnDelta: 0, valuationDelta: -3, investorDelta: -2, riskDelta: 2 },
    },
    event: {
      name: "New Compliance Requirements for Fintech",
      description: "Regulators announced stricter capital requirements and KYC/AML rules. Compliance costs are rising sharply.",
      type: "negative",
      severity: 70,
      affectedSectors: ["Fintech", "DeFi", "Payments", "Lending"],
      affectedRegions: ["North America", "Europe"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "consumer_recession",
    name: "Consumer Recession",
    description: "Households are cutting spending. B2C startups are struggling to acquire and retain customers.",
    condition: "bearish",
    macro: {
      ...BASE_MACRO,
      consumerSpending: -50,
      vcClimate: -30,
      inflationPressure: 20,
    },
    sectorModifiers: {
      "b2c": { demandDelta: -25, revenueDelta: -20, burnDelta: 0, valuationDelta: -20, investorDelta: -15, riskDelta: 15 },
      "ecommerce": { demandDelta: -20, revenueDelta: -15, burnDelta: 0, valuationDelta: -15, investorDelta: -10, riskDelta: 10 },
      "gaming": { demandDelta: -10, revenueDelta: -8, burnDelta: 0, valuationDelta: -10, investorDelta: -5, riskDelta: 5 },
      "saas": { demandDelta: -5, revenueDelta: -3, burnDelta: 0, valuationDelta: -5, investorDelta: -3, riskDelta: 3 },
    },
    event: {
      name: "Consumer Confidence at Lows",
      description: "Retail spending dropped for three consecutive quarters. Customer acquisition costs are rising while lifetime values shrink.",
      type: "negative",
      severity: 75,
      affectedSectors: ["B2C", "E-commerce", "Gaming", "Consumer Apps"],
      affectedRegions: ["North America", "Europe", "Asia"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "enterprise_software_budget_expansion",
    name: "Enterprise Expansion",
    description: "CIOs are expanding software budgets. B2B SaaS and infrastructure are booming.",
    condition: "bullish",
    macro: {
      ...BASE_MACRO,
      enterpriseSpending: 50,
      vcClimate: 30,
      aiDemand: 20,
    },
    sectorModifiers: {
      "saas": { demandDelta: 20, revenueDelta: 18, burnDelta: -3, valuationDelta: 20, investorDelta: 12, riskDelta: -5 },
      "enterprise": { demandDelta: 20, revenueDelta: 18, burnDelta: -3, valuationDelta: 20, investorDelta: 12, riskDelta: -5 },
      "cybersecurity": { demandDelta: 15, revenueDelta: 12, burnDelta: 0, valuationDelta: 15, investorDelta: 10, riskDelta: -3 },
      "ai": { demandDelta: 15, revenueDelta: 12, burnDelta: 0, valuationDelta: 15, investorDelta: 10, riskDelta: -3 },
    },
    event: {
      name: "CIOs Accelerate Digital Transformation",
      description: "Enterprise software budgets expanded 15% YoY. Procurement cycles are shortening for mission-critical tools.",
      type: "positive",
      severity: 60,
      affectedSectors: ["SaaS", "Enterprise Software", "Cybersecurity", "AI / ML"],
      affectedRegions: ["North America", "Europe"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "supply_chain_crisis",
    name: "Supply Chain Crisis",
    description: "Global shipping and component shortages are raising costs for hardware and logistics startups.",
    condition: "bearish",
    macro: {
      ...BASE_MACRO,
      supplyChainPressure: 70,
      inflationPressure: 30,
      energyPrices: 20,
    },
    sectorModifiers: {
      "hardware": { demandDelta: -15, revenueDelta: -10, burnDelta: 10, valuationDelta: -15, investorDelta: -10, riskDelta: 15 },
      "logistics": { demandDelta: -10, revenueDelta: -8, burnDelta: 8, valuationDelta: -10, investorDelta: -8, riskDelta: 12 },
      "manufacturing": { demandDelta: -10, revenueDelta: -8, burnDelta: 8, valuationDelta: -10, investorDelta: -8, riskDelta: 12 },
      "saas": { demandDelta: 0, revenueDelta: 0, burnDelta: 0, valuationDelta: -2, investorDelta: -1, riskDelta: 1 },
    },
    event: {
      name: "Component Shortages and Port Congestion",
      description: "Critical component lead times extended to 6+ months. Logistics costs are up 40% and hardware startups face delays.",
      type: "negative",
      severity: 70,
      affectedSectors: ["Hardware", "Logistics", "Manufacturing", "Robotics"],
      affectedRegions: ["Asia", "Europe", "North America"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "energy_price_spike",
    name: "Energy Shock",
    description: "Energy prices have spiked. Data center costs are rising and climate tech is attracting capital.",
    condition: "bearish",
    macro: {
      ...BASE_MACRO,
      energyPrices: 70,
      inflationPressure: 30,
      consumerSpending: -10,
    },
    sectorModifiers: {
      "climate": { demandDelta: 15, revenueDelta: 12, burnDelta: 0, valuationDelta: 15, investorDelta: 10, riskDelta: -3 },
      "energy": { demandDelta: 10, revenueDelta: 8, burnDelta: 3, valuationDelta: 10, investorDelta: 7, riskDelta: 0 },
      "ai": { demandDelta: -5, revenueDelta: -3, burnDelta: 8, valuationDelta: -5, investorDelta: -3, riskDelta: 5 },
      "data_center": { demandDelta: -5, revenueDelta: -3, burnDelta: 8, valuationDelta: -5, investorDelta: -3, riskDelta: 5 },
    },
    event: {
      name: "Power Costs Surge for Data Centers",
      description: "Electricity prices up 60% in key regions. AI training costs are rising and climate tech is seeing renewed investor interest.",
      type: "negative",
      severity: 65,
      affectedSectors: ["AI / ML", "Data Center", "Climate Tech", "Energy"],
      affectedRegions: ["Europe", "North America", "Asia"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
  {
    key: "healthcare_ai_tailwind",
    name: "Healthcare AI Tailwind",
    description: "Regulatory approvals for AI diagnostics are accelerating. Healthcare AI is attracting record funding.",
    condition: "bullish",
    macro: {
      ...BASE_MACRO,
      aiDemand: 50,
      vcClimate: 30,
      regulationPressure: -10,
    },
    sectorModifiers: {
      "healthcare": { demandDelta: 20, revenueDelta: 18, burnDelta: -2, valuationDelta: 20, investorDelta: 15, riskDelta: -8 },
      "ai": { demandDelta: 10, revenueDelta: 8, burnDelta: 0, valuationDelta: 10, investorDelta: 7, riskDelta: -3 },
      "biotech": { demandDelta: 10, revenueDelta: 8, burnDelta: 0, valuationDelta: 10, investorDelta: 7, riskDelta: -3 },
    },
    event: {
      name: "FDA Fast-Tracks AI Diagnostics",
      description: "Regulatory pathway cleared for AI-driven diagnostic tools. Healthcare AI funding hit record highs this quarter.",
      type: "positive",
      severity: 60,
      affectedSectors: ["Healthtech", "Biotech", "AI / ML"],
      affectedRegions: ["North America", "Europe"],
    },
    gameplayEffects: {
      demandDelta: 0,
      revenueDelta: 0,
      burnDelta: 0,
      valuationDelta: 0,
      investorDelta: 0,
      riskDelta: 0,
    },
  },
];

export function getScenarioByKey(key: string): MarketScenario | undefined {
  return SCENARIOS.find((s) => s.key === key);
}

export function getAllScenarios(): MarketScenario[] {
  return SCENARIOS;
}
