-- AlterTable
ALTER TABLE "founder_profiles" ADD COLUMN     "bestMonthlyRevenue" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bestOutcome" TEXT,
ADD COLUMN     "bestStartupId" TEXT,
ADD COLUMN     "completedStartupIds" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "founderRank" TEXT NOT NULL DEFAULT 'rookie',
ADD COLUMN     "founderTitle" TEXT NOT NULL DEFAULT 'Rookie Founder',
ADD COLUMN     "lastCompletedStartupId" TEXT,
ADD COLUMN     "legacyBadges" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "playstyleStats" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "recentRuns" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "reputationScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rivalStats" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "sectorStats" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "totalAcquisitions" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalBreakouts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalMonthsPlayed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalRevenueGenerated" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalSeriesAReady" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalSurvived12" INTEGER NOT NULL DEFAULT 0;
